//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Lombard.ImageExchange.Nab.OutboundService.Messages.XsdImports {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class Voucher {
        
        private string accountNumberField;
        
        private string amountField;
        
        private string auxDomField;
        
        private string bsbNumberField;
        
        private string documentReferenceNumberField;
        
        private DocumentTypeEnum documentTypeField;
        
        private string extraAuxDomField;
        
        private System.DateTime processingDateField;
        
        private string transactionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auxDom {
            get {
                return this.auxDomField;
            }
            set {
                this.auxDomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsbNumber {
            get {
                return this.bsbNumberField;
            }
            set {
                this.bsbNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentReferenceNumber {
            get {
                return this.documentReferenceNumberField;
            }
            set {
                this.documentReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentTypeEnum documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extraAuxDom {
            get {
                return this.extraAuxDomField;
            }
            set {
                this.extraAuxDomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime processingDate {
            get {
                return this.processingDateField;
            }
            set {
                this.processingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum DocumentTypeEnum {
        
        /// <remarks/>
        CRT,
        
        /// <remarks/>
        DBT,
        
        /// <remarks/>
        HDR,
        
        /// <remarks/>
        Bh,
        
        /// <remarks/>
        Cr,
        
        /// <remarks/>
        Dr,
        
        /// <remarks/>
        Sp,
        
        /// <remarks/>
        SUP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class RegionOfInterest {
        
        private int heightField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherBatch {
        
        private string batchAccountNumberField;
        
        private string batchTypeField;
        
        private string captureBsbField;
        
        private string clientField;
        
        private string collectingBankField;
        
        private StateEnum processingStateField;
        
        private string scannedBatchNumberField;
        
        private string sourceField;
        
        private string subBatchTypeField;
        
        private string unitIDField;
        
        private WorkTypeEnum workTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchAccountNumber {
            get {
                return this.batchAccountNumberField;
            }
            set {
                this.batchAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchType {
            get {
                return this.batchTypeField;
            }
            set {
                this.batchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string captureBsb {
            get {
                return this.captureBsbField;
            }
            set {
                this.captureBsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string collectingBank {
            get {
                return this.collectingBankField;
            }
            set {
                this.collectingBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StateEnum processingState {
            get {
                return this.processingStateField;
            }
            set {
                this.processingStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scannedBatchNumber {
            get {
                return this.scannedBatchNumberField;
            }
            set {
                this.scannedBatchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subBatchType {
            get {
                return this.subBatchTypeField;
            }
            set {
                this.subBatchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitID {
            get {
                return this.unitIDField;
            }
            set {
                this.unitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkTypeEnum workType {
            get {
                return this.workTypeField;
            }
            set {
                this.workTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum StateEnum {
        
        /// <remarks/>
        NSW,
        
        /// <remarks/>
        QLD,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        VIC,
        
        /// <remarks/>
        WA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum WorkTypeEnum {
        
        /// <remarks/>
        BQL_INWARDFV,
        
        /// <remarks/>
        BQL_POD,
        
        /// <remarks/>
        NABCHQ_APOST,
        
        /// <remarks/>
        NABCHQ_INWARDFV,
        
        /// <remarks/>
        NABCHQ_INWARDNFV,
        
        /// <remarks/>
        NABCHQ_LBOX,
        
        /// <remarks/>
        NABCHQ_LISTINGS,
        
        /// <remarks/>
        NABCHQ_POD,
        
        /// <remarks/>
        NABCHQ_SURPLUS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherProcess {
        
        private string adjustedByField;
        
        private bool adjustedFlagField;
        
        private string adjustmentDescriptionField;
        
        private bool adjustmentLetterRequiredField;
        
        private int adjustmentReasonCodeField;
        
        private string alternateAccountNumberField;
        
        private string alternateAuxDomField;
        
        private string alternateBsbNumberField;
        
        private string alternateExAuxDomField;
        
        private string alternateTransactionCodeField;
        
        private int apMatchAttemptsField;
        
        private System.Nullable<APPresentmentTypeEnum> apPresentmentTypeField;
        
        private bool creditNoteFlagField;
        
        private string customerLinkNumberField;
        
        private System.Nullable<System.DateTime> documentRetrievalDateField;
        
        private bool documentRetrievalFlagField;
        
        private System.Nullable<ForValueTypeEnum> forValueTypeField;
        
        private bool highValueFlagField;
        
        private bool inactiveFlagField;
        
        private bool isGeneratedBulkCreditField;
        
        private bool isGeneratedVoucherField;
        
        private bool isReservedForBalancingField;
        
        private bool isRetrievedVoucherField;
        
        private string listingPageNumberField;
        
        private int manualRepairField;
        
        private bool micrFlagField;
        
        private string operatorIdField;
        
        private bool postTransmissionQaAmountFlagField;
        
        private bool postTransmissionQaCodelineFlagField;
        
        private string preAdjustmentAmountField;
        
        private string presentationModeField;
        
        private string rawMICRField;
        
        private string rawOCRField;
        
        private System.Nullable<ReleaseStatusEnum> releaseFlagField;
        
        private string repostFromDRNField;
        
        private System.Nullable<System.DateTime> repostFromProcessingDateField;
        
        private bool surplusItemFlagField;
        
        private bool suspectFraudField;
        
        private bool thirdPartyCheckFailedField;
        
        private bool thirdPartyMixedDepositReturnFlagField;
        
        private bool thirdPartyPoolFlagField;
        
        private string transactionLinkNumberField;
        
        private bool unencodedECDReturnFlagField;
        
        private bool unprocessableField;
        
        private string voucherDelayedIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adjustedBy {
            get {
                return this.adjustedByField;
            }
            set {
                this.adjustedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool adjustedFlag {
            get {
                return this.adjustedFlagField;
            }
            set {
                this.adjustedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adjustmentDescription {
            get {
                return this.adjustmentDescriptionField;
            }
            set {
                this.adjustmentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool adjustmentLetterRequired {
            get {
                return this.adjustmentLetterRequiredField;
            }
            set {
                this.adjustmentLetterRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adjustmentReasonCode {
            get {
                return this.adjustmentReasonCodeField;
            }
            set {
                this.adjustmentReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternateAccountNumber {
            get {
                return this.alternateAccountNumberField;
            }
            set {
                this.alternateAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternateAuxDom {
            get {
                return this.alternateAuxDomField;
            }
            set {
                this.alternateAuxDomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternateBsbNumber {
            get {
                return this.alternateBsbNumberField;
            }
            set {
                this.alternateBsbNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternateExAuxDom {
            get {
                return this.alternateExAuxDomField;
            }
            set {
                this.alternateExAuxDomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternateTransactionCode {
            get {
                return this.alternateTransactionCodeField;
            }
            set {
                this.alternateTransactionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int apMatchAttempts {
            get {
                return this.apMatchAttemptsField;
            }
            set {
                this.apMatchAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<APPresentmentTypeEnum> apPresentmentType {
            get {
                return this.apPresentmentTypeField;
            }
            set {
                this.apPresentmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool creditNoteFlag {
            get {
                return this.creditNoteFlagField;
            }
            set {
                this.creditNoteFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerLinkNumber {
            get {
                return this.customerLinkNumberField;
            }
            set {
                this.customerLinkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> documentRetrievalDate {
            get {
                return this.documentRetrievalDateField;
            }
            set {
                this.documentRetrievalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool documentRetrievalFlag {
            get {
                return this.documentRetrievalFlagField;
            }
            set {
                this.documentRetrievalFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<ForValueTypeEnum> forValueType {
            get {
                return this.forValueTypeField;
            }
            set {
                this.forValueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool highValueFlag {
            get {
                return this.highValueFlagField;
            }
            set {
                this.highValueFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool inactiveFlag {
            get {
                return this.inactiveFlagField;
            }
            set {
                this.inactiveFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGeneratedBulkCredit {
            get {
                return this.isGeneratedBulkCreditField;
            }
            set {
                this.isGeneratedBulkCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGeneratedVoucher {
            get {
                return this.isGeneratedVoucherField;
            }
            set {
                this.isGeneratedVoucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isReservedForBalancing {
            get {
                return this.isReservedForBalancingField;
            }
            set {
                this.isReservedForBalancingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isRetrievedVoucher {
            get {
                return this.isRetrievedVoucherField;
            }
            set {
                this.isRetrievedVoucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string listingPageNumber {
            get {
                return this.listingPageNumberField;
            }
            set {
                this.listingPageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int manualRepair {
            get {
                return this.manualRepairField;
            }
            set {
                this.manualRepairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool micrFlag {
            get {
                return this.micrFlagField;
            }
            set {
                this.micrFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool postTransmissionQaAmountFlag {
            get {
                return this.postTransmissionQaAmountFlagField;
            }
            set {
                this.postTransmissionQaAmountFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool postTransmissionQaCodelineFlag {
            get {
                return this.postTransmissionQaCodelineFlagField;
            }
            set {
                this.postTransmissionQaCodelineFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string preAdjustmentAmount {
            get {
                return this.preAdjustmentAmountField;
            }
            set {
                this.preAdjustmentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presentationMode {
            get {
                return this.presentationModeField;
            }
            set {
                this.presentationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rawMICR {
            get {
                return this.rawMICRField;
            }
            set {
                this.rawMICRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rawOCR {
            get {
                return this.rawOCRField;
            }
            set {
                this.rawOCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<ReleaseStatusEnum> releaseFlag {
            get {
                return this.releaseFlagField;
            }
            set {
                this.releaseFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string repostFromDRN {
            get {
                return this.repostFromDRNField;
            }
            set {
                this.repostFromDRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> repostFromProcessingDate {
            get {
                return this.repostFromProcessingDateField;
            }
            set {
                this.repostFromProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool surplusItemFlag {
            get {
                return this.surplusItemFlagField;
            }
            set {
                this.surplusItemFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool suspectFraud {
            get {
                return this.suspectFraudField;
            }
            set {
                this.suspectFraudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool thirdPartyCheckFailed {
            get {
                return this.thirdPartyCheckFailedField;
            }
            set {
                this.thirdPartyCheckFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool thirdPartyMixedDepositReturnFlag {
            get {
                return this.thirdPartyMixedDepositReturnFlagField;
            }
            set {
                this.thirdPartyMixedDepositReturnFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool thirdPartyPoolFlag {
            get {
                return this.thirdPartyPoolFlagField;
            }
            set {
                this.thirdPartyPoolFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionLinkNumber {
            get {
                return this.transactionLinkNumberField;
            }
            set {
                this.transactionLinkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool unencodedECDReturnFlag {
            get {
                return this.unencodedECDReturnFlagField;
            }
            set {
                this.unencodedECDReturnFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool unprocessable {
            get {
                return this.unprocessableField;
            }
            set {
                this.unprocessableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string voucherDelayedIndicator {
            get {
                return this.voucherDelayedIndicatorField;
            }
            set {
                this.voucherDelayedIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum APPresentmentTypeEnum {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum ForValueTypeEnum {
        
        /// <remarks/>
        Inward_For_Value,
        
        /// <remarks/>
        Inward_Non_For_Value,
        
        /// <remarks/>
        Outward_For_Value,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum ReleaseStatusEnum {
        
        /// <remarks/>
        reject,
        
        /// <remarks/>
        release,
        
        /// <remarks/>
        release_sent,
        
        /// <remarks/>
        reject_by_user,
        
        /// <remarks/>
        reject_by_system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class CodelineStatus {
        
        private bool accountNumberStatusField;
        
        private bool amountStatusField;
        
        private bool auxDomStatusField;
        
        private bool bsbNumberStatusField;
        
        private bool extraAuxDomStatusField;
        
        private bool transactionCodeStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool accountNumberStatus {
            get {
                return this.accountNumberStatusField;
            }
            set {
                this.accountNumberStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool amountStatus {
            get {
                return this.amountStatusField;
            }
            set {
                this.amountStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool auxDomStatus {
            get {
                return this.auxDomStatusField;
            }
            set {
                this.auxDomStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bsbNumberStatus {
            get {
                return this.bsbNumberStatusField;
            }
            set {
                this.bsbNumberStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool extraAuxDomStatus {
            get {
                return this.extraAuxDomStatusField;
            }
            set {
                this.extraAuxDomStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool transactionCodeStatus {
            get {
                return this.transactionCodeStatusField;
            }
            set {
                this.transactionCodeStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherInformation {
        
        private Voucher voucherField;
        
        private VoucherBatch voucherBatchField;
        
        private VoucherImage[] voucherImageField;
        
        private VoucherProcess voucherProcessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Voucher voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherBatch voucherBatch {
            get {
                return this.voucherBatchField;
            }
            set {
                this.voucherBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voucherImage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherImage[] voucherImage {
            get {
                return this.voucherImageField;
            }
            set {
                this.voucherImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherProcess voucherProcess {
            get {
                return this.voucherProcessField;
            }
            set {
                this.voucherProcessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherImage {
        
        private byte[] contentField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/ImageExchangeVoucherDetails")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/ImageExchangeVoucherDetails", IsNullable=false)]
    public partial class ImageExchangeVoucher {
        
        private Voucher voucherField;
        
        private VoucherBatch voucherBatchField;
        
        private VoucherProcess voucherProcessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Voucher voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherBatch voucherBatch {
            get {
                return this.voucherBatchField;
            }
            set {
                this.voucherBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherProcess voucherProcess {
            get {
                return this.voucherProcessField;
            }
            set {
                this.voucherProcessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ForValueReference {
        
        private ForValueDetails[] forValueDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forValueDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForValueDetails[] forValueDetails {
            get {
                return this.forValueDetailsField;
            }
            set {
                this.forValueDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ForValueDetails {
        
        private string accountNumberField;
        
        private string bsbField;
        
        private DocumentTypeEnumStore documentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsb {
            get {
                return this.bsbField;
            }
            set {
                this.bsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentTypeEnumStore documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum DocumentTypeEnumStore {
        
        /// <remarks/>
        Bh,
        
        /// <remarks/>
        Cr,
        
        /// <remarks/>
        Dr,
        
        /// <remarks/>
        Sp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class BusinessCalendar {
        
        private System.DateTime businessDayField;
        
        private System.DateTime[] closedDaysField;
        
        private bool inEndOfDayField;
        
        private bool isEndOfMonthField;
        
        private bool isEndOfWeekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime businessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("closedDays", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime[] closedDays {
            get {
                return this.closedDaysField;
            }
            set {
                this.closedDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool inEndOfDay {
            get {
                return this.inEndOfDayField;
            }
            set {
                this.inEndOfDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isEndOfMonth {
            get {
                return this.isEndOfMonthField;
            }
            set {
                this.isEndOfMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isEndOfWeek {
            get {
                return this.isEndOfWeekField;
            }
            set {
                this.isEndOfWeekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class AgencyBankDetails {
        
        private string[] bsbField;
        
        private ImageExchangeType fileTypeField;
        
        private string fourCharactersEndpointNameField;
        
        private bool includeCreditField;
        
        private string targetEndpointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bsb", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] bsb {
            get {
                return this.bsbField;
            }
            set {
                this.bsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ImageExchangeType fileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fourCharactersEndpointName {
            get {
                return this.fourCharactersEndpointNameField;
            }
            set {
                this.fourCharactersEndpointNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool includeCredit {
            get {
                return this.includeCreditField;
            }
            set {
                this.includeCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string targetEndpoint {
            get {
                return this.targetEndpointField;
            }
            set {
                this.targetEndpointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    public enum ImageExchangeType {
        
        /// <remarks/>
        AgencyXML,
        
        /// <remarks/>
        Cuscal,
        
        /// <remarks/>
        ImageExchange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ValueInstructionFile {
        
        private string ackFileWaitPeriodField;
        
        private int maxQuerySizeField;
        
        private RecordTypeCode[] recordTypeCodesField;
        
        private string slaPeriodField;
        
        private ValueInstructionFileWorkTypeGroup[] targetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ackFileWaitPeriod {
            get {
                return this.ackFileWaitPeriodField;
            }
            set {
                this.ackFileWaitPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxQuerySize {
            get {
                return this.maxQuerySizeField;
            }
            set {
                this.maxQuerySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordTypeCodes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecordTypeCode[] recordTypeCodes {
            get {
                return this.recordTypeCodesField;
            }
            set {
                this.recordTypeCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string slaPeriod {
            get {
                return this.slaPeriodField;
            }
            set {
                this.slaPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ValueInstructionFileWorkTypeGroup[] targets {
            get {
                return this.targetsField;
            }
            set {
                this.targetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class RecordTypeCode {
        
        private string accountNumberField;
        
        private string bsbField;
        
        private string codeField;
        
        private string transactionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsb {
            get {
                return this.bsbField;
            }
            set {
                this.bsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ValueInstructionFileWorkTypeGroup {
        
        private ValueInstructionFileTarget[] targetDetailsField;
        
        private WorkTypeEnum workTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ValueInstructionFileTarget[] targetDetails {
            get {
                return this.targetDetailsField;
            }
            set {
                this.targetDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkTypeEnum workType {
            get {
                return this.workTypeField;
            }
            set {
                this.workTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ValueInstructionFileTarget {
        
        private string batchTypeField;
        
        private string captureBsbField;
        
        private string collectingBsbField;
        
        private string financialInstitutionField;
        
        private StateEnum stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchType {
            get {
                return this.batchTypeField;
            }
            set {
                this.batchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string captureBsb {
            get {
                return this.captureBsbField;
            }
            set {
                this.captureBsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string collectingBsb {
            get {
                return this.collectingBsbField;
            }
            set {
                this.collectingBsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string financialInstitution {
            get {
                return this.financialInstitutionField;
            }
            set {
                this.financialInstitutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StateEnum state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class AgencyBanksImageExchange {
        
        private AgencyBankDetails[] agencyBanksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agencyBanks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgencyBankDetails[] agencyBanks {
            get {
                return this.agencyBanksField;
            }
            set {
                this.agencyBanksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class StateOrdinal {
        
        private int ordinalField;
        
        private StateEnum stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StateEnum state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class AssetManagement {
        
        private AssetRetention[] assetRetentionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("assetRetention", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AssetRetention[] assetRetention {
            get {
                return this.assetRetentionField;
            }
            set {
                this.assetRetentionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class AssetRetention {
        
        private string assetNameField;
        
        private int retentionDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int retentionDays {
            get {
                return this.retentionDaysField;
            }
            set {
                this.retentionDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class EndOfDayWorkflow {
        
        private string[] workflowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workflowName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] workflowName {
            get {
                return this.workflowNameField;
            }
            set {
                this.workflowNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class TierOneBanksImageExchange {
        
        private int maxQuerySizeField;
        
        private string[] targetEndpointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxQuerySize {
            get {
                return this.maxQuerySizeField;
            }
            set {
                this.maxQuerySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetEndpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] targetEndpoint {
            get {
                return this.targetEndpointField;
            }
            set {
                this.targetEndpointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class ImageExchange {
        
        private string[] targetEndpointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetEndpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] targetEndpoint {
            get {
                return this.targetEndpointField;
            }
            set {
                this.targetEndpointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class StateOrdinals {
        
        private StateOrdinal[] stateOrdinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stateOrdinal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StateOrdinal[] stateOrdinal {
            get {
                return this.stateOrdinalField;
            }
            set {
                this.stateOrdinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class SchedulerDetails {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("batchType", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("endOfWeekDelay", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("processName", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("recurringInterval", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("startTime", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("workType", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":batchType")]
        batchType,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":endOfWeekDelay")]
        endOfWeekDelay,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":processName")]
        processName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":recurringInterval")]
        recurringInterval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":startTime")]
        startTime,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":workType")]
        workType,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Metadata", IsNullable=false)]
    public partial class SchedulerReference {
        
        private SchedulerDetails[] schedulerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scheduler", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SchedulerDetails[] scheduler {
            get {
                return this.schedulerField;
            }
            set {
                this.schedulerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/CreateImageExchangeFile")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/CreateImageExchangeFile", IsNullable=false)]
    public partial class CreateImageExchangeFileResponse {
        
        private string imageExchangeFilenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageExchangeFilename {
            get {
                return this.imageExchangeFilenameField;
            }
            set {
                this.imageExchangeFilenameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/CreateImageExchangeFile")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/CreateImageExchangeFile", IsNullable=false)]
    public partial class CreateImageExchangeFileRequest {
        
        private System.DateTime businessDateField;
        
        private ImageExchangeType fileTypeField;
        
        private string fourCharactersEndPointField;
        
        private string jobIdentifierField;
        
        private int sequenceNumberField;
        
        private string targetEndPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime businessDate {
            get {
                return this.businessDateField;
            }
            set {
                this.businessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ImageExchangeType fileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fourCharactersEndPoint {
            get {
                return this.fourCharactersEndPointField;
            }
            set {
                this.fourCharactersEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobIdentifier {
            get {
                return this.jobIdentifierField;
            }
            set {
                this.jobIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string targetEndPoint {
            get {
                return this.targetEndPointField;
            }
            set {
                this.targetEndPointField = value;
            }
        }
    }
}
