CREATE TABLE IF NOT EXISTS REF_FOR_VALUE(
  ID INT NOT NULL PRIMARY KEY,
  BSB NVARCHAR(6),
  ACC NVARCHAR(17),
  DOCUMENT_TYPE NVARCHAR(10),
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_REF_FOR_VALUE ON REF_FOR_VALUE (ID);
