CREATE TABLE IF NOT EXISTS ref_metadata(
  ref_id int NOT NULL auto_increment  PRIMARY KEY,
  ref_name NVARCHAR(50) NOT NULL,
  ref_value NVARCHAR(65536) NOT NULL
);

INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('ValueInstructionFile' , '{ "maxQuerySize": 7998, "ackFileWaitPeriod": "PT1M", "slaPeriod": "PT10M", "targets": [ { "workType": "NABCHQ_POD", "targetDetails": [ { "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "state": "SA", "financialInstitution": "NAB", "collectingBsb": "085384", "captureBsb": "085015" }, { "state": "WA", "financialInstitution": "NAB", "collectingBsb": "086038", "captureBsb": "086016" }, { "state": "QLD", "financialInstitution": "NAB", "collectingBsb": "084024", "captureBsb": "084014" }, { "state": "QLD", "financialInstitution": "BQL", "collectingBsb": "124001", "captureBsb": "124001" } ] }, { "workType": "NABCHQ_LBOX", "targetDetails": [ { "batchType": "LCG1", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LML1", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LCS1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LRD1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LSV1", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LBC1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LCW1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LCY1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LEG1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LRD2", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LGS1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LMC1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LPC1", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LSV2", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LSV3", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LSV4", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LHS1", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LSV5", "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082082" }, { "batchType": "LNC1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LEA1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LRC1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" }, { "batchType": "LOW1", "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083340" } ] }, { "workType": "NABCHQ_APOST", "targetDetails": [ { "state": "NSW", "financialInstitution": "NAB", "collectingBsb": "082037", "captureBsb": "082265" }, { "state": "VIC", "financialInstitution": "NAB", "collectingBsb": "083029", "captureBsb": "083309" }, { "state": "SA", "financialInstitution": "NAB", "collectingBsb": "085384", "captureBsb": "085265" }, { "state": "WA", "financialInstitution": "NAB", "collectingBsb": "086038", "captureBsb": "085265" }, { "state": "QLD", "financialInstitution": "NAB", "collectingBsb": "084024", "captureBsb": "084265" } ] } ], "recordTypeCodes": [ { "code": "C", "transactionCode": "111" }, { "code": "C", "transactionCode": "222" }, { "code": "P", "bsb": "377872" }, { "code": "P", "bsb": "377873" }, { "code": "P", "bsb": "377874" }, { "code": "P", "bsb": "377876" }, { "code": "P", "bsb": "377877" }, { "code": "P", "bsb": "377878" }, { "code": "P", "bsb": "401795" }, { "code": "P", "bsb": "430327" }, { "code": "P", "bsb": "430328" }, { "code": "P", "bsb": "430329" }, { "code": "P", "bsb": "430330" }, { "code": "P", "bsb": "433687" }, { "code": "P", "bsb": "455701" }, { "code": "P", "bsb": "455702" }, { "code": "P", "bsb": "455703" }, { "code": "P", "bsb": "455704" }, { "code": "P", "bsb": "471527" }, { "code": "P", "bsb": "490292" }, { "code": "P", "bsb": "490289" }, { "code": "P", "bsb": "531355" }, { "code": "P", "bsb": "531356" }, { "code": "P", "bsb": "531357" }, { "code": "P", "bsb": "531358" }, { "code": "P", "bsb": "531359" }, { "code": "P", "bsb": "552061" }, { "code": "P", "bsb": "552270" }, { "code": "P", "bsb": "555001" }, { "code": "P", "bsb": "556733" }, { "code": "P", "bsb": "558388" } ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('StateOrdinals' , '{ "stateOrdinals": [ { "state": "NSW", "ordinal": "2" }, { "state": "VIC", "ordinal": "3" }, { "state": "QLD", "ordinal": "4" }, { "state": "SA", "ordinal": "5" }, { "state": "WA", "ordinal": "6" } ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('TierOneBanksImageExchange', '{ "maxQuerySize": 1, "targetEndpoints": [ "FIS", "ANZ", "RBA" ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('AgencyBanksImageExchange', '{ "agencyBanks": [ { "targetEndpoint": "MQG", "fourCharactersEndpointName": "MACQ", "bsbs": [ "18" ], "fileType": "AGENCY_XML", "includeCredit": false }, { "targetEndpoint": "BQL", "fourCharactersEndpointName": "BOQL", "bsbs": [ "12", "653", "639" ], "fileType": "AGENCY_XML", "includeCredit": true }, { "targetEndpoint": "JPM", "fourCharactersEndpointName": "JPMB", "bsbs": [ "21", "915" ], "fileType": "AGENCY_XML", "includeCredit": false }, { "targetEndpoint": "CIT", "fourCharactersEndpointName": "CITI", "bsbs": [ "24" ], "fileType": "AGENCY_XML", "includeCredit": true }, { "targetEndpoint": "ARB", "fourCharactersEndpointName": "ARAB", "bsbs": [ "917" ], "fileType": "AGENCY_XML", "includeCredit": true }, { "targetEndpoint": "CUS", "bsbs": [ "51", "80", "31", "64", "81" ], "fileType": "CUSCAL", "includeCredit": true } ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('ReportMetadata', '{ "reportGroups": [ { "frequency": "END_OF_DAY", "reports": [ { "reportName": "NAB_VIF_Transmission_Report", "reportType": "NAB VIF Transmission Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB VIF Transmission Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "transmissiondate" } ] }, { "reportName": "BQL_VIF_Transmission_Report", "reportType": "BQL VIF Transmission Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "BQL VIF Transmission Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "transmissiondate" } ] }, { "reportName": "Agency_ECD_Exception_Single_Item_Report", "reportType": "Agency Bank ECD Return Single Item Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointName": "Email1", "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s ECD Exception Return Single Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "Agency_ECD_Exception_Return_All_Items_Report", "reportType": "Agency Bank ECD Return All Items Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointName": "Email1", "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s ECD Exception Return All Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "Agency_Unprocessable_Paper_Report", "reportType": "Agency Bank Unprocessable Paper Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointName": "Email1", "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s ECD Exception Return All Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "NAB_ECD_Exception_Report", "reportType": "NAB ECD Exception Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB ECD Exception Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "Agency_Inward_For_Value_DR_Report", "reportType": "Agency Bank Inward FV DR Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointName": "Email1", "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s Inward For Value DR Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "NAB_Inward_For_Value_DR_Report", "reportType": "NAB Inward FV Debit Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Inward For Value DR Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Outward_For_Value_CR_Report", "reportType": "NAB Outward For Value Credit Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Outward For Value CR Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "BQL_Outward_For_Value_CR_Report", "reportType": "BQL Outward For Value Credit Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "BQL Outward For Value CR Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_High_Value_Report", "reportType": "NAB High Value Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "NAB High Value Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Adjustments_Letter_Report", "reportType": "NAB Adjustments Letter Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Adjustments Letter Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "Agency_Bank_Adjustments_Letter_Report", "reportType": "Agency Bank Adjustments Letter Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s Adjustment Letter Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "NAB_Adjustments_Report", "reportType": "NAB Adjustments Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Adjustments Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_IPOD_Errors_Report", "reportType": "NAB IPOD Errors Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB IPOD Errors Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "BQL_IPOD_Errors_Report", "reportType": "BQL IPOD Errors Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "BQL IPOD Errors Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "Agency_IPOD_Errors_Report", "reportType": "Agency Bank IPOD Errors Report", "formatType": "XLSX", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s IPOD Errors Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "NAB_All_Items_Report", "reportType": "NAB All Items Report", "formatType": "TXT", "deliveryEndpoints": [ { "endpointType": "B_2_B" } ], "outputFilenamePattern": "PROD.FXA.NAB.RPT.AIR.%1$tY%1$tm%1$td.%3$s", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "STATE", "ssrsName": "processingstate" }, { "metadataName": "STATE_ORDINAL", "ssrsName": "stateordinal" } ] }, { "reportName": "BQL_All_Items_Report", "reportType": "BQL All Items Report", "formatType": "TXT", "deliveryEndpoints": [ { "endpointType": "B_2_B" } ], "outputFilenamePattern": "PROD.FXA.BQL.RPT.AIR.%1$tY%1$tm%1$td.%3$s", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "STATE_ORDINAL", "ssrsName": "stateordinal" } ] }, { "reportName": "NAB_Document_Retrieval_Report", "reportType": "NAB Document Retrieval Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Document Retrieval %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "BQL_Document_Retrieval_Report", "reportType": "BQL Document Retrieval Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "BQL Document Retrieval %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "Agency_Surplus_Items_Report", "reportType": "Agency Bank Surplus Items Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "%2$s Surplus Items Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "AGENCY_BANK", "ssrsName": "agencybank" }, { "metadataName": "AGENCY_BANK_GROUP", "ssrsName": "agencybankgroup" } ] }, { "reportName": "NAB_LockedBox_Daily_Report", "reportType": "NAB Locked Box DAILY Processing Details", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Locked Box Daily Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Incoming_Suspect_Fraud_Report", "reportType": "NAB Incoming Suspect Fraud Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Incoming Suspect Fraud %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Outbound_Image_Exchange_Report", "reportType": "NAB Outbound Image Exchange Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Outbound Image Exchange Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "transmissiondate" } ] }, { "reportName": "NAB_Inbound_Image_Exchange_Report", "reportType": "NAB Inbound Image Exchange Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Inbound Image Exchange Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "transmissiondate" } ] }, { "reportName": "NAB_Over_100K_Report", "reportType": "NAB Over $100k Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "Over $100k Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Outgoing_Suspect_Fraud_Report", "reportType": "NAB Outgoing Suspect Fraud Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Outgoing Suspect Fraud %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Daily_Volumes_Report", "reportType": "NAB Daily Volumes Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Daily Volumes Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_QA_Report", "reportType": "NAB QA Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB QA Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Merchant_Substitutes_Report", "reportType": "NAB Daily Merchant Substitutes Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Merchant Substitute Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Document_Retrieval_Request_Report", "reportType": "NAB Document Retrieval Request Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Request for Document Retrieval %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] }, { "reportName": "NAB_Daily_Issues_Report", "reportType": "NAB Daily Issues", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "Daily Log NAB[%2$s]_[%1$tY%1$tm%1$td]", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" }, { "metadataName": "STATE", "ssrsName": "processingstate" } ] }, { "reportName": "FXA_QA_Report", "reportType": "FXA QA Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "FXA QA Report %1$tY%1$tm%1$td", "parameterDefinitions": [ { "metadataName": "BUSINESS_DAY", "ssrsName": "processdate" } ] } ] }, { "frequency": "END_OF_MONTH", "reports": [ { "reportName": "NAB_LockedBox_MONTHLY_Processing_Details", "reportType": "NAB Locked Box MONTHLY Processing Details", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Locked Box Monthly Report %2$tY%2$tm%2$td", "parameterDefinitions": [ { "metadataName": "START_MONTH_DATE", "ssrsName": "startdate" }, { "metadataName": "BUSINESS_DAY", "ssrsName": "enddate" } ] }, { "reportName": "NAB_Daily_Listings", "reportType": "NAB Daily Listings Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "DOCUMENTUM" } ], "outputFilenamePattern": "NAB Daily Listings %2$tY%2$tm%2$td", "parameterDefinitions": [ { "metadataName": "START_MONTH_DATE", "ssrsName": "startdate" }, { "metadataName": "BUSINESS_DAY", "ssrsName": "enddate" } ] }, { "reportName": "NAB_Monthly_Volumes_Report", "reportType": "NAB MONTHLY Volumes Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "NAB Monthly Volumes Report %2$tY%2$tm%2$td", "parameterDefinitions": [ { "metadataName": "START_MONTH_DATE", "ssrsName": "startdate" }, { "metadataName": "BUSINESS_DAY", "ssrsName": "enddate" } ] }, { "reportName": "NAB_Billing_Report", "reportType": "NAB Billing Report", "formatType": "CSV", "deliveryEndpoints": [ { "endpointType": "EMAIL" } ], "outputFilenamePattern": "NAB Billing Report %2$tY%2$tm%2$td", "parameterDefinitions": [ { "metadataName": "START_MONTH_DATE", "ssrsName": "startdate" }, { "metadataName": "BUSINESS_DAY", "ssrsName": "enddate" } ] } ] } ], "emailConfigurations": [ { "endpointName": "Email1", "body": "Some email body message", "from": "from@email.com", "to": "to@email.com", "cc": "cc@email.com", "subject": "Some email subject message" } ]}');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('AssetManagement', '{ "assetRetentions": [ { "assetName": "bitlocker", "retentionDays": 30 }, { "assetName": "jobdb", "retentionDays": 30 }, { "assetName": "camundadb", "retentionDays": 60 } ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('ForValueReference', '{"forValueReference":[{"bsb":"013133", "accountNumber":"291895392", "documentType":"Cr"}, {"bsb": "013133", "accountNumber":"291895691", "documentType":"Cr"},  {"bsb":"013133", "accountNumber":"291895966", "documentType":"Cr"}, {"bsb":"013133", "accountNumber":"291896272", "documentType":"Cr"}, {"bsb":"013133", "accountNumber":"291896424", "documentType":"Cr"}, {"bsb":"032898", "accountNumber": "055135", "documentType":"Cr"}, {"bsb":"063978", "accountNumber":"10069630", "documentType":"Cr"}, {"bsb":"063978", "accountNumber":"10069665", "documentType":"Cr"}, {"bsb":"063978", "accountNumber": "10076750", "documentType":"Cr"}, {"bsb":"063978", "accountNumber":"10076769", "documentType":"Cr"}, {"bsb":"083029", "accountNumber":"823300223", "documentType":"Cr"}, {"bsb":"092002",  "accountNumber":"815545", "documentType":"Cr"}, {"bsb":"093003", "accountNumber":"814704", "documentType":"Cr"}, {"bsb":"094004", "accountNumber":"814458",  "documentType":"Cr"}, {"bsb":"095005", "accountNumber":"814548", "documentType":"Cr"}, {"bsb":"096006", "accountNumber":"814494", "documentType":"Cr"}, {"bsb":"124001", "accountNumber":"10457814", "documentType":"Cr"}, {"bsb": "082039", "accountNumber":"999999912", "documentType":"Dr"}, {"bsb":"083029",  "accountNumber":"823300223", "documentType":"Dr"}]}');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('AdjustmentLettersMetadata', '{ "letters": [ { "customers": [ { "accountNumber": "515096734", "bsb": "083001" } ], "outputFilenamePrefix": "coles" }, { "customers": [ { "accountNumber": "537447494", "bsb": "083355" }, { "accountNumber": "037558307", "bsb": "083355" }, { "accountNumber": "036056284", "bsb": "084092" }, { "accountNumber": "048720189", "bsb": "083355" }, { "accountNumber": "478225567", "bsb": "084092" }, { "accountNumber": "036057615", "bsb": "083355" }, { "accountNumber": "036057228", "bsb": "084092" }, { "accountNumber": "666986080", "bsb": "082001" } ], "outputFilenamePrefix": "super" }, { "customers": [ { "bsb": "51" }, { "bsb": "80" }, { "bsb": "31" }, { "bsb": "64" }, { "bsb": "81" } ], "outputFilenamePrefix": "cuscal" } ] }');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('ReportAgencyBanksMetadata', '{ "agencyBanks": [ { "agencyBankGroupCode": "ARA", "agencyBankName": "Arab Bank Australia Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "ADC", "agencyBankName": "Australian Defence Credit Union", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "BQL", "agencyBankName": "Bank of Queensland Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "LBA", "agencyBankName": "Bank of Sydney Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "BBL", "agencyBankName": "Bendigo and Adelaide Bank Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "ADL", "agencyBankName": "Bendigo and Adelaide Bank Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CAP", "agencyBankName": "Capricornian Ltd (The)", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CTI", "agencyBankName": "Citigroup Pty Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CFC", "agencyBankName": "Community First Credit Union Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CUA", "agencyBankName": "Credit Union Australia Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CRU", "agencyBankName": "Cuscal Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "HBA", "agencyBankName": "HSBC Bank Australia Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "IBK", "agencyBankName": "Industrial and Commercial Bank of China Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "CMB", "agencyBankName": "JP Morgan Chase Bank, NA", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "MBL", "agencyBankName": "Macquarie Bank Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "MCU", "agencyBankName": "mecu Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "OCB", "agencyBankName": "Oversea-Chinese Banking Corporation Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "PCU", "agencyBankName": "Police Bank Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "QTM", "agencyBankName": "QT Mutual Bank Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "TCU", "agencyBankName": "Teachers Mutual Bank Limited", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "HSB", "agencyBankName": "The Hong Kong & Shanghai Banking Corporation Limited, Australia Branch", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "RBS", "agencyBankName": "The Royal Bank of Scotland PLC, Australia Branch", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_Inward_For_Value_DR_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] }, { "agencyBankGroupCode": "WCU", "agencyBankName": "Warwick Credit Union Ltd", "includeReports": [ "Agency_Bank_Adjustments_Letter_Report", "Agency_ECD_Exception_Single_Item_Report", "Agency_ECD_Exception_Return_All_Items_Report", "Agency_IPOD_Errors_Report", "Agency_Surplus_Items_Report", "Agency_Unprocessable_Paper_Report" ] } ]}');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('AusPostECLMatch', '{"maxMatchAttempts": 3}');
INSERT INTO ref_metadata (ref_name, ref_value) VALUES ('EncodedDummyImage', '{
	"encodedImageDetails": [{
		"imageType": "INSERTED_CREDIT_FRONT",
		"imageContent": "/9j/4AAQSkZJRgABAQEAZABkAAD//gAySUFBSUZHOkRFODc5MDE0QzI1NDM4NkQ0OUQyNjI5Rjcz
NUE1RkM4RUVFNzE2QzQ6/9sAQwACAQECAQECAgICAgICAgMFAwMDAwMGBAQDBQcGBwcHBgcHCAkL
CQgICggHBwoNCgoLDAwMDAcJDg8NDA4LDAwM/8AACwgA/wJyAQERAP/EAB4AAQACAwADAQEAAAAA
AAAAAAAICQEHCgIFBgQD/8QARxAAAQIEAwIJCwMCBAQHAAAAAAECAwQFBgcIEQkSExkaIVdYl9TV
ChQxODl2d5KTtLUVIkEWUSMyQmEzcZGhGCQnOnSys//aAAgBAQAAPwCwvZmbM3Ldfuzfy+1yuZe8
EK1W61hrbk/UKhP2LS5man5iLS5Z8WNFivgK+JEe9znOe5VVyqqqqqpvHinsrPVpy/8AZ7SO7jin
srPVpy/9ntI7uOKeys9WnL/2e0ju44p7Kz1acv8A2e0ju44p7Kz1acv/AGe0ju44p7Kz1acv/Z7S
O7jinsrPVpy/9ntI7uOKeys9WnL/ANntI7uOKeys9WnL/wBntI7uOKeys9WnL/2e0ju44p7Kz1ac
v/Z7SO7jinsrPVpy/wDZ7SO7jinsrPVpy/8AZ7SO7jinsrPVpy/9ntI7uOKeys9WnL/2e0ju44p7
Kz1acv8A2e0ju44p7Kz1acv/AGe0ju44p7Kz1acv/Z7SO7jinsrPVpy/9ntI7uOKeys9WnL/ANnt
I7uOKeys9WnL/wBntI7uOKeys9WnL/2e0ju44p7Kz1acv/Z7SO7jinsrPVpy/wDZ7SO7jinsrPVp
y/8AZ7SO7jinsrPVpy/9ntI7uOKeys9WnL/2e0ju44p7Kz1acv8A2e0ju44p7Kz1acv/AGe0ju44
p7Kz1acv/Z7SO7jinsrPVpy/9ntI7uOKeys9WnL/ANntI7uOKeys9WnL/wBntI7uOKeys9WnL/2e
0ju44p7Kz1acv/Z7SO7jinsrPVpy/wDZ7SO7jinsrPVpy/8AZ7SO7jinsrPVpy/9ntI7uOKeys9W
nL/2e0ju44p7Kz1acv8A2e0ju44p7Kz1acv/AGe0ju44p7Kz1acv/Z7SO7jinsrPVpy/9ntI7uOK
eys9WnL/ANntI7uOKeys9WnL/wBntI7uOKeys9WnL/2e0ju44p7Kz1acv/Z7SO7jinsrPVpy/wDZ
7SO7jinsrPVpy/8AZ7SO7jinsrPVpy/9ntI7uOKeys9WnL/2e0ju44p7Kz1acv8A2e0ju44p7Kz1
acv/AGe0ju44p7Kz1acv/Z7SO7jinsrPVpy/9ntI7uOKeys9WnL/ANntI7uOKeys9WnL/wBntI7u
OKeys9WnL/2e0ju44p7Kz1acv/Z7SO7jinsrPVpy/wDZ7SO7jinsrPVpy/8AZ7SO7jinsrPVpy/9
ntI7uOKeys9WnL/2e0ju44p7Kz1acv8A2e0ju44p7Kz1acv/AGe0ju44p7Kz1acv/Z7SO7jinsrP
Vpy/9ntI7uOKeys9WnL/ANntI7uOKeys9WnL/wBntI7uOKeys9WnL/2e0ju44p7Kz1acv/Z7SO7j
insrPVpy/wDZ7SO7jinsrPVpy/8AZ7SO7jinsrPVpy/9ntI7uOKeys9WnL/2e0ju44p7Kz1acv8A
2e0ju44p7Kz1acv/AGe0ju5R5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv+IlSQAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABzeZUPVaw191aX9pCLw9k77LLLT8KrX/ESpIAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA5vMqHqtYa+6tL+0hF4eyd9lllp+FVr/AIiVJAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv+IlSQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAABzeZUPVaw191aX9pCLw9k77LLLT8KrX/ABEqSAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAObzKh6rWGvurS/tIReHsnfZZZafhVa/4iVJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv+IlSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAABzeZUPVaw191aX9pCLw9k77LLLT8KrX/ESpIAAAAAAAAAAa6gADUAagAAADUDUDUAagAAa
gAAAAAAAAAAAAA5vMqHqtYa+6tL+0hF4eyd9lllp+FVr/iJUkAAAAAAAAY00VVK086nlSuX/ACJZ
obrwlu+z8YqlclnR4UvOzNHpVNiyUR0SBDjtWG+LPw3qm7Fai7zG86L6U0VZHYp7WPC/CDZtyGaS
pQrkmcO6lSpCqwJOUl4EWrPSciQ4UOX4NYyQeGbEio16cNutVj/3Lpz6d2bflGeCO1FzFrhlh/au
KtHriUuYqqx7hpshLyfBQVYjm70CdjP314RuibmnMvOhP5FTe0QxvLqn8J/KHnrz/wBkMa6qHLz+
j0BF019CGEVNdPSY3lVU/hP5QhPlB27+EedLPRdmX217bxHp952dEqcOdnapT5OFS4qyEwkCNwcS
HNRIq7z11ZvQm6p6d1eYZQdvFhFnTz1XZl9ta28R5C87OiVOHOztVp8lCpcVZCYSBG4OJDm4kVd5
66s3oTdU9O6vMTY0/wCqHk3m05+Y/hVJ9tMp8eaejlhy0N0RyInOqNTVdP8AoQR2a/lDeC+1IzET
mGlgWxijSK7IUmPWYkxcFOkZeTWDCiQobmo6BORn76uit0RWImiLzpzIs9f49BjVUHpdrz8w009C
84RddDH9uZOcy7nRU0I+5+Np7gps0LJlKzi3eMGhRKtwv6TSpeBEnKnWHwmK9zYMCGiu013WrFib
kFrojEfEbvJru+z7ml7ztSmViVhxoctVJWFNwmxERHtbEYj2o7RVTXRU10VU1/lT2euqGVTm/wCR
pnPxnctXZ25XrjxbvSn3DVLbth0s2blqJAgxp2IseYhy7NxsaLCYuj4rVXV6cyLpqvMvrNnRtCrM
2m2WyUxSsKl3PSLem5+YpzJevy0CBOb8ByNeqtgxozN1VXmXf1/uiG6riuGStGhTtVqk9J06l02A
+am5uaitgwJWCxqufEiPcqNaxrUVVcqoiIiqpWBjr5X3lKwbxFmaDS24mYiy8q1N+sWzQ5daesTV
yOhsdOzMtEerdP8AO2GsNyORWvchLLZw7XDBPam2TN1LC24Jp1VpLGxKtbtXl/M6xSUc5WsWJDRz
mPY7T/iQYkRiK5Gq5HatSTioif7jfT+eYIuqHii6Q9V5lIe7VLbYYWbIqcsmDiTQMQK4t+NnHSH9
NSMnMpB814FInC+cTUDd14dm7u72ujtdObX0G0M2+uEGzToOGFRvu2sSqrAxZpL6zSEoVPkph8tB
Y2A5WzCRpuCjX6TDOZivTmdz8ya76zIbQPCTJ5gDTcTsUrwk7HtOqtl/NYs7CiR5qYiR2o5kKHLw
GxIsaIjVVzmwmv3Wte5dGtVyfV5Zcw1CzXYAWniTa8KoQrdvOnQ6pT2z0FsGZSDETVu+xrnI1VTn
03l9JsBOcAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAADxe79qnKltL8tbs
3vlKOMWHUCE2NPXJCnGU9rlRrVnYVq8NLaqqLonDw4fP/BravZ56lmK2LmB2U6ixI83eMLE+cl2y
LIicJHlXbr5NjmoqO3XzVSjNajkVNZX0puoiSu8nrwjp2X/ykbF2xqSjYdMs6WuaiyrUTRODl52F
Cbzar/DP7qe/2huNGLNzbQC5pHFDaMUHCGTV01J0GzsFpi47gnqe6HNPhwKbMylPgysFJ1VVzYjp
mZ4ff3W7qQ9xGfSeTKbTPHO4NoteWAOJl9YiX7bcWVqkzLNvxIjq/SZ6UiQ2/wCLw8SNHl1WFDe2
JKLGeyHEVVbz77n6MydZpM7Oa3aRY+4M4Q4z3I6sV+LXJOWnrxuufmaXZ8hAqOr40rDc2YSDGVqM
lob4UJXQ0jqrdxUR7Ny+Tk7QXMTae1iu7Lji/iVc+I8in6vT51K7WI9bdIVKmq7WLLTMw5YrYTkg
xW7iLuu32uViOTVP0eTm5zMYMcNtPila964rYl3fbNOo9diytGrVzT1Qp8s+HUZdkNzIEWK6G1WN
c5rVRqbqKqJoinsdkXnFxexJ8pPxasW4cVcR6/ZNNrF3QpS3alcs7NUmVZBmojYLYcrEiLCakNER
GIjU3UTRND5DaG4z4tXNtALmkcUdoxQcIZNXTUnQbOwWmLjuCep7oc0+HApszKU+DKwUnVVXNiOm
Znh9/dbupD3EZ9J5MntM8c7g2i95YA4mX1iJfttxZWqTMs2/EiOr9JnpSJCb/i8PEjR5dVhQ3tiS
ixnshxFVW8++5/wmwF/9zZjpz86zV5flEPx7CmjJcflI+YOmvjzkqyoLess+PKTDpeYgo+pI1Xw4
jVRzHprqjmqioqIqc6G1diNnfxcykbZTGPLtj/ixfl5UyUkqlCkJm8Llmaokq+nI6chTMJZiI9Ib
Y0hwsV25pqiM1T9vN9B5ONmExo2lO04xqxhuHE7E+ZwntePMx6Xas5cc6+jwo1RjRklJdJThPN92
BLQ4n7UZo13Bu0RdFLxL0dpaVU/+LE/+inMX5Heum1oub+/9CVL7uSP35Oc0ednNbtIcfMGcIMZ7
kdWLgi1yTlp68brn5ml2fIQKjq+NKw3NmEgxlajJaG+FCV0NI6q3cVEezcvk5G0FzFWptYrty44v
4kXNiPJJ+r06cSu1iPWnU+o07e1iy0zMOWK2E5IMVqsRd12+1ysRyapH3GzaL4x5gdovixbuYHOF
itlBlrSmZuTpElblJqsemwuCmnJCk3y1NjQIquWFER7ZqIyKsRjU1eicGi2N7CDPBf1iZHMZLqxJ
zFYcZlLOwwpEzcEjN0ys1SNddMbBZMRo0CeZU5KWmlgxdz/Aixt5UVj2MVzEajK88smc/HTbJ4zY
k3biDn5kspVNt+Az9CpH9V/09JTqxosd8KUgS8Ock+EhwWpuxJqIsaNo6CjuE/0y48m52yWK+Y+o
YqYDYs3g6+6rZtuTVXtm6Vi8POvhSytl40KJNt55lur4UWHHiaxV1ib0R6KxGQL2VmKGffai1+88
JsM8xN9ScTzeWuCqXBc98Vhr6dDlnvhsl4E3DWNHgpGfM6uZCanC8Azedus0XPlNeT7FrKlmGw/Z
iFilWMTLaq9BgytsxKrcE/VJ2VfJSNPl6hHismUVsF0zNb0ZUhPfva6uVFRELD65mCzEbBXYSVuu
Yj4hyuJWK9/XNBk7Hqsetzteh0CUm6dBWHr59Causu2WmYjYKNdBR72a7yOc1YHU/GrHi5shE7ma
j7SGYkMU21GJWYWEf9erCnY0Js7uLpJNnUhscujojZJJJYSwd1OZHbiTGrHlJWJ9U8nxZilAjSEv
jn/VzMOJitwqdD4BI/m6zX6kkBU4FIrpZuitRqw0jOVyQ0ZpDSIGNeW3NhcuwamsxN4ZmL3veyL/
AJmXgVqw7kqExVmwqeyqJCl5qFMTMeKjI3nUGA5WQocNyQ3KixFTehra95ImqLseaN/tc9W//Vp+
zysvFqvYYbIO4pahTU1JsumvU6iVKJAe5jllHufFiQ1VP9L1gtY5F5nNeqLqi6LG/wAlM2ZGAuM2
z2qWJF9YaWRiPddw3FNyEaLc1Hl6xDpsCWRiQ4MGFHa9kJV33Pc5qI9++1FVWtaiTI2dOxayp5PM
2N94l4O1WoVa8qdPxqZNU2FdaTcpZL4rXOi09JaXVqtRzIkNeCnljPakOE5u6qarS7h/mVzp5str
HjTgThDjnf0tOXbcVw0aWfWbuqX6da8jL1B8wsaXVroiyatZLNgtiQYavayK5jNN/VJCbYHaEZhd
kVlbwdys0rFuu1jFyuUGPXb9xCmKxHqM/HbNzExChykpOTiLFgQ2KkREjpwcVrYEFzVhKrtdIZm8
2OO+yBunDK/cPNoNS80cxWWuh3Bbv9XLcshTYjOBiPl40tEnZnfgRf3sbMtSXjIjXbvBq7VJDeUI
7c/FG6LUwIsXAm4a5h9Axgs2m3vUp+lTTpKqOSdi6S0nCm2q2JBRj4T1iOhqxX6tRXbm+10NvKGM
mOP2SJcG7cxix2rWPFGqMjUKhRqhWEiPnqROuWWSfleFjRY0eLBTSVVjnRd3/PpDhrvb0svKXM22
K+WTCHKBAw2xOxEw+hVixoz56FbVxzlJbPOZBpyMWKkvEYj1ajnIiu103l09KnovK2sHMUp2wcFM
UZ69o05hVUaLSqIy3ItYm4kT9c83nI8SfdKub5vq6Cu4sbfWKq/tVN3nJv8AkrmVfG/A7KfGu/Er
Ef8ArCwcRaHRp2wqJ+vz9Q/piVhpNLFhebzENsGV3kiwU3ZdzmrwfOv7W62sAAAAAAAAAA5vMqHq
tYa+6tL+0hF4eyd9lllp+FVr/iJUkAAAAAAAAeC6uRebVdCliR2S+YGD5UMuYp1gf+jS1lZpLh/X
Kb/wv0HzTe828485/wCP+zTgtf503ec1NlS8nFxbwq290LECr2TBlsAbcvaeumj1n9Yp8dIkNvCz
MhC824ZZlFbHWCxVdCTTg1X0aON0bNPZQ4+4B+UBY3Y2XbYrqJhheE3c8Sk11tapswsw2dnkiyzk
l4cd8du8zV2j4SbumjtF5iN2TfY+bQTZQZ9bwr+D9gYZYgylxwYtAg3ncdSlFp6SkxHhRlnuA87h
T0GKzcThGNZETVIiI2Om45dm7HvY15qclG2sn8TcUbXZdNqVhtYZVL5lK1TEgz0zNwnRVmvNOHSa
RkSPqzTgGuTfRVY1qLp9ZsStklmEyh7ZfFrFjETD5bdsG5pavw6ZVP1ymzfnLpmpQY8BOBgTD4zd
6G1zv3MTTTRdF5j12zc2QOYnATyg69McLsw8Wk4XVe4bpnpStfrtMj8LBnFmvNnebwpl0wm/wjOZ
YaK3X9yN0U0fUdhZn2yR7UK7r1yyxaRJ0W6KpNMkrzfUaT5rJU6emOEfDm5SdWJGXgf276w5eK5e
CR0PedohtvYz7EfMrkg2yFxYg4i0mJWbLiytZgf11+q05XVuYmU1SZ80bMxJlixYiudo+Hqn+pE9
BqzJvsfNoJsoM+t4V/CCwMMsQZS44MWgQbzuOpSi09JSYjwoyz3Aedwp6DFZuJwjGsiJqkREbHTc
cuzdj1sa81OSfbWT+JuKNrsum1Kw2sMql8ytapiQZ6Zm4ToqzXmnDpNIyJH1ZpwDXJvoqsa1F0+s
2QmyQzCZXdujivjHfOH36Hhxcse5XU2r/rlNmfOEm59I0t/gQZh8du/DTX90NN30O0XmM7ITZI5h
cru3RxWxjvrD79Cw2uaPcr6bV/1ymzPnCTc+kaXXgIMw+O3fhpr+6Gm76HaLzEc/LKsA5LCPNxht
i3b1eh0u479oc3RKrJyk3wM7EZLNSEkxo3Ryw4svMul3qq6KkNG6KiqhaB5Nhkp/8GWyrsVs9Kwo
FzYis/rGrORm7E/821rpZjtURdWSqQEVq+hyvJ2XJKxJ+3J6DBbvRI0u9jG66aqrVRE5yinybTYy
ZlMgu0Ort74tYbf0pas5ac9TIM9/UFLnt+YiTMq9jODlZmLETVsN66q3RNOdUVU1+02JOyRzC5Q9
sti1ixiJh8tu2Dc0rXodNqn65TZvzl0zUoMeAnAwJh8Zu9Da537mJppoui8x63Zv7IDMXgL5QTe+
N914fOo2GFZr91TsnXUrtMmFfCnFmvNXpLw5h8dN/hGczoWrdf3Imimc2OV3aZyuYiek69h5gFnX
w6p3nL7YW/LatjzWnMixv2RFhPWQmYU4kKExIiMe+AqRNEWIrUVnvdhV5P1iTgReOMWIOP1Nt+zG
4u23U7VdYVvzcOLCkZWfj70ffdBc+Xhw2shtbAhw4kbRkX9ysczdWMOH+wazgbNfF69KTYGXvLnm
ntG4Ibf0+s3vS6TOpItZEipDfDgz81LxpaZ3FRYjGLFgLvNRHRFbqlgGxZ2V+M+WvD6872xxp+EF
Lv25qJFpNGt6zbBtmix6TCiNR0TzufpkjAWJFe9rGpChxnwGtbvK6I5zeC1F5LRsm8fNnNi3i3V8
Z8Pm2dLXLSqfK0qP+tU2oumHw4sZ8ViJKTEVzERFYv7kRF5tNdOb6/ypDY+Yw7Sej4VXJg3SJK6a
zZDp+Rn6LFqMtT48SFNLLvbHhxJl8OCqMWAqOa6Ijv3tVqO/dp9Bd+z8zFbW3Y71vCTMladp4P4s
21V5eNZkeQmIU7T47JOVhtl40z5vNzStWLvzUGI5rkViPR7YTtEY6AeHGyPz7YNYLwcIqVlHys1d
KdU3wZbE2r27alYrboCzO9wixJ2M/hYCprpw8k6YSE7dRGua1Gz+xo2AFx4x7F+PgdU7hw5h4wxa
tCvBapQLRpttW8tWY1YaQEg06Sl9YPm7nQfOHwljOVd9URukFsHZTZkbTTEfZaTeV6sWBZFCw8tK
M2qSLJi4JCLX7jTzp8dlOhRoU7ElmwWR3pG/x0gKjYaIkR2iQnWg+Tn5NcSciGzbplg4rW4trXbL
16ozkSR/UJWe3YMWI1YbuElosSHzoi8yO1T+UQkbn2yX2xtB8pt4YR3bEmJak3ZKthtnJdE4enTE
OI2LAmGIvMrocVjHbq6I5EVq8yqUS4LbKDapbJ2v3PZ2XepyFZs6tzEOeiztKqtBjU6bio1WpEbL
VndiS8fc3WxFhw0R24xOEiJDYqSh2C/k9GJWWXM1FzI5kazLTuJUVJuZp1FWf/VJyWnZrfZHnZ6b
RXQ4kdWOi6NhviovDb6xEcm6nqtkRsi8wOWLbp4p4y37h42i4dXBNXLGpNZdW6bMrF88nuEl1SBB
mHx2K+Eqr+6Gm6iqjtF5jaflJGwpvHaaPtPE7CWao0TEex5CNTpiiVSI2BDuGTRzo8GHBjP1hMjs
jOiNRkbdhPSYXeiQ9zR8TLV2VeenMxiVaVDrOWTJrlzt6QhcFWLklMN7Nq/n7EWGjosSA5J+I+Y3
UerGQWy8JznKj3MTdVu/PKBPJ/b8zWWVhNdmX6HTaheGE9BgWstD1kaFEqUlCiI6BGleDZLycCJC
e+K90JOBhbrl4NGq1Ib4t7UDZcbS3anWzhzdWJeHFhxaxactHo8rbFvV+nyseUbq10Wozb4866Xd
FmFbCREl4zk0g88KD/r3t5Qzsf8AMVnlsDLFI4W4eLdM1h5acemXCz9dpkj+nzLoUg1rNZmZhpE1
WDE54aub+3086ayP2+my1xO2g+zHw/s7DyRkp2/LAn5CqLRZiegy36ijJOJLRoMONEckFIjVio5F
e9rFRjv3a7qL9jsAbYzWYM5d34W5j8L7dsKhYdUyn0yy5+nVSUnJmqwW8Okds15vOTDd9iJA0cjI
SKjncyqmpYMnoAAAAAAAAABzeZUPVaw191aX9pCLw9k77LLLT8KrX/ESpIAAAAAAAA8U5+dBzK4a
p/uOZfRzaBU5vQY/nX/uFVd7Qzva8w/ypzhPR/celNfTqY/3/wC4RDwmJdk1LxIURqPZEarXNVNU
VF5lQqxwx8kCyo4fYv06656fxUu2Wp846cWgVusybqTNquu7DitgScKM6G1yoqN4VN7dRHbzVc11
pcrKQ5GXhQoMNkGDBajGMY1GtYiJoiIicyIifwf3Vf8AcN9CLpoYVdXHlrqp4pzN5zKcyoPSvOF5
+b+BvaN/5B3o1/kLz+ga86hdOdP7DnT/AGH+ow7mTXTnGi6c/MoRmv8APoGn/Mz6E/vp6TComqGd
0LpoNUXUwrefmUyjub06nkAAAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv8AiJUkAAAAAAAA
AAAAAANAAAAAANAANAAAANAABpoAAAAAAAAAAc3mVD1WsNfdWl/aQi8PZO+yyy0/Cq1/xEqSAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAObzKh6rWGvurS/tIReHsnfZZZafhVa/4iVJAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv8AiJUkAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc3mVD1WsNfdWl/aQi8PZO+yyy0/Cq1/xEqSAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAObzKh6rWGvurS/tIReHsnfZZZafhVa/4iVJAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8AESpIAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA5vMqHqtYa+6tL+0hF4eyd9lllp+FVr/iJUkAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAc3mVD1WsNfdWl/aQi8PZO+yyy0/Cq1/xEqSAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAObzKh6rWGvurS/tIReHsnfZZZafhVa/4iVJAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAHN5lQ9VrDX3Vpf2kIvD2TvssstPwqtf8RKkgAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAADm8yoeq1hr7q0v7SEXh7J32WWWn4VWv8AiJUkAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAc3mVD1WsNfdWl/aQi8PZO+yyy0/Cq1/xEqSAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAObzKh6rWGvurS/tIReHsnfZZZafhVa/4iVJAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAHN5lQ9VrDX3Vpf2kInlkk20dDy2ZMMIsPK5gjjfNVqwLLo9t1CPILbcSVjTEn
IQYEV8Jz6wx7oauhuVquY1VRU1ai8ybR5QhZ3QRmA+W2PGhyhCzugjMB8tseNDlCFndBGYD5bY8a
HKELO6CMwHy2x40OUIWd0EZgPltjxocoQs7oIzAfLbHjQ5QhZ3QRmA+W2PGhyhCzugjMB8tseNDl
CFndBGYD5bY8aHKELO6CMwHy2x40OUIWd0EZgPltjxocoQs7oIzAfLbHjQ5QhZ3QRmA+W2PGhyhC
zugjMB8tseNDlCFndBGYD5bY8aHKELO6CMwHy2x40OUIWd0EZgPltjxocoQs7oIzAfLbHjQ5QhZ3
QRmA+W2PGhyhCzugjMB8tseNDlCFndBGYD5bY8aHKELO6CMwHy2x40OUIWd0EZgPltjxocoQs7oI
zAfLbHjQ5QhZ3QRmA+W2PGhyhCzugjMB8tseNDlCFndBGYD5bY8aHKELO6CMwHy2x40OUIWd0EZg
PltjxocoQs7oIzAfLbHjQ5QhZ3QRmA+W2PGhyhCzugjMB8tseNDlCFndBGYD5bY8aHKELO6CMwHy
2x40OUIWd0EZgPltjxocoQs7oIzAfLbHjQ5QhZ3QRmA+W2PGhyhCzugjMB8tseNH8H+UQ2PDcrVw
Lx/1aui/4ds+NGOUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OU
R2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR
2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2
P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P
0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0
GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0G
ZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZ
gPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40OUR2P0GZgPp2z40Vs5e7enrEwDseh1SEkrU6Nb8
hIzcHhEfwMaFLQ2PbvN1aujmqmrVVF05lVD/2Q=="
	},
	{
		"imageType": "INSERTED_CREDIT_REAR",
		"imageContent": "/9j/4AAQSkZJRgABAQEAZABkAAD//gAySUFBSUZHOkRFODc5MDE0QzI1NDM4NkQ0OUQyNjI5Rjcz
NUE1RkM4RUVFNzE2QzQ6/9sAQwACAQECAQECAgICAgICAgMFAwMDAwMGBAQDBQcGBwcHBgcHCAkL
CQgICggHBwoNCgoLDAwMDAcJDg8NDA4LDAwM/8AACwgA/wJyAQERAP/EAB4AAQACAgMBAQEAAAAA
AAAAAAAICgEHAgYJBQME/8QARRAAAQIEAwIKCQQBAwMDBQAAAAECAwQFBgcIEQkSExkaITlXWJfU
1QoUMXZ3kpO1thUiI0EWFzJRKGFxJJGhM0KBo7T/2gAIAQEAAD8Am5sd9ntgHjhkKot03rgfg/eF
zVS6ru9cq9bs6nVCfm+DuiqwofCR40F0R+7DYxibyro1jUTmREJQcU9lZ7NOX/u9pHhxxT2Vns05
f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZW
ezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keH
HFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7v
aR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NO
X/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2V
ns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHH
FPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC7
2keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezT
l/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9l
Z7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhx
xT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72
keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl
/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZ
WezTl/7vaR4ccU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4c
cU9lZ7NOX/u9pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9
pHhxxT2Vns05f+72keHHFPZWezTl/wC72keHHFPZWezTl/7vaR4ccU9lZ7NOX/u9pHhynttM7Qpl
h7SHMFQ6FTKbRaJRcSrjkKfT5GCyWlZGXhVSZZCgwoTNGw4bGNa1rGoiNRERERELZGwk6M61/eq8
/wAsrBMEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVe
f5ZWCYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/
yysEwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkHtYulNzLfFW6Pu80Wu9hJ0Z1r+9V5/l
lYJggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFIPaxdKbmW+Kt0fd5otd7CTozrX96rz/LK
wTBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQe1i6U3Mt8Vbo+7zRa72EnRnWv71Xn+WVg
mCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUg9rF0puZb4q3R93mi13sJOjOtf3qvP8srBM
EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYI
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/wAsrBME
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYIA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/yysEwQAA
AAAAAAAAAAAAAAAAAAAAAAAAANdQAAAAAAAAACkHtYulNzLfFW6Pu80Wu9hJ0Z1r+9V5/llYJggA
AAAAAAAHDXdVf+NCN2TvawYG54cS7osWxbva6/rJmZmWrNs1KWfJ1GW4CZiS74jEcnBzEPehoqvg
PiIxIsLf3HPRprST28+EE5tPFynstzEj/UVtRfTP1FZCS/ROEbJrOKvC+t8Nu8GiprwGu9zaac5m
09vLhFeW01mcqUpbmJDMRZapTNLdUYtPkkoqxZeVfNPVIqTaxt1WMVEXgdd7TVETnJuJrrz8wX+9
f7C86KYVy/8AlDX2ZnNLYGTbB6p39ibc8haVp0fdSZn5pHv/AHOXRkOHDhtdEixHL7IcNrnLouiL
op5oyfpmuVSYuaFT32vjdLS0WaSXdUotBp6ysJiv3Vjua2eWNwaJ+5UbDV+iczFd+09KcrWbPDrO
lg9I37hfdlOvG1Kg90OFOyiPYsOI3TehRYURrYsGI3VFWHEa16I5qqmioq9rxCvWVwzw/rlxz8OY
iyVBkY9SmGQGo6K+HBhuiORiOVEVyo1dEVUTX+09pFfZYba3Cza8zl6wsNrfxAobrEbJvn/8lkpO
WSN61w6Q+C9Xmo+9pwD97e3dNW6a8+kxFXReYwi6OXm5v6C6K3mXT/uRtw62seBmI2cu5cvzLwSj
4uWxORJR1Bqks+WdUtyDCjK+VjaLBjasi6pDR6RtIUR3Bo1quJJp/wC2pnnRDjvaIn9GVMNRGqqm
VXXn0Cv5yM21A2qGH2yaweod74iUe8q1Sbgq7aLLwrclJaZmGRlgxY289seYgNRm7CcmqOVdVTm0
1VO55B87lq7RLK7buLdlU+4KXblyumWSstW4MGDPQ1gTESXfvsgxYrE1fCcqaPXmVNdF5k3N7V5w
ic5F/ah7V7DvZLYYW7d2I9GvSt025aq6kSsO25SWmI8OKkJ0VXPSPMQGozdaqao5V105v7Oh5ptv
BhFlEyU4UY8XLbmI87aGMEOBEo0nTJCSiVKVSNLLMN9YZEm2Q26MRUXciP8A3f8AKc5J7LJmCo2a
7LvZmJVvytUk6FfdIlq3IQKjDZDm4MGOxIjGxWw3vY16Iqao17k19iqd99uvN/8Akyi/0hlV50OO
9+9NE9v/AMBFTUz7fb7TGmjOYjBtRtq/h3sl8Lrdu7EejXrWqdc1UWkysO25SVmY8OKkJ0VXPSPM
QGozdYqao5V105v7Ou7K/bXYS7XZ95w8NqXfFFmbGWUdPy1zSMrLRYjJnheDfC9XmI7XNRYL0XeV
qounMuupGjGP0wDLJgri3dFnTto401SctSrTVImJ2mUmlxZKbiS8Z0J0SC91Ra50NysVWq5rVVqo
qonsPUq3q7DuSgyVQgte2DPQGTENr0RHI16I5NdFVNdF/pVPopzoAAAAAAACkHtYulNzLfFW6Pu8
0Wu9hJ0Z1r+9V5/llYJggAAAAAAAAEedqRgFirmeyQ3lZOCt7f6eYkVhZJaTX/1icpHqKQp2BFjf
+plGPjw9+CyIz9jV3t/dXRFVStHsRssuM987bKHblsYhfo122JXY9TvWqfrk9LrcUhJVSA2oy/DQ
2LEmPWHc+5HRrInterVJwUTORi9H9Llfhs/FXEd2HX+URoCWqtzTq0RISUN8VGep8JwO6kREfu7m
m9z+3nIvY4YcYlYw+lQ3xa2Et5f6fXvX7wnpGVuRILYz6LLPpz2zceGx3tiNleH3N1Wu393dfDdo
9u88tedHMpshNu3TMu2JeNl5Y42RdVapVCmpi5J6Yn1jwp5jPVZyXbMR40STiQ4kyiRGMiK16Mcj
kfpDc38M8+1Uxa2iu1+ruBdBzMQcqGDNkVedpf8AkbKx+hJvyLYsONMTExw8vEjxI0ZHMhy6x4cJ
GpDXd32ue7hs9tq5izkl2t0vlvuzMS/NBg7e1ag0CXulle/VXLFqEOC2WnJWf4WNGgvhvcyHEgJM
PhMcsZW/v0iGtdrvQc+uyAtOUoFy5lb8uiw7/uGNPUG4qbe1Xi1iT9TbEYyWjzERYcSDwsGZbEfA
Y+JCc+AjkXWHqvqjCyP4U7VLYe4D1LMrd9zSkCi2TTq/M3pMXW6SmKdHfAgrMTkxGmlfLRXPa1zH
RZqHEVrYkRWqxzt4+5mI2HGUmn7L66bat7DOxWytIs2YnqZe0CTloleiRIMu6ZhTzqm1qRYu89rX
u/fwT2KrN1IejU85fQncVq/K5gcZrG9anIlrzlBla06XV7lgQJyHMJBSIjfY174cVUVU0VyQm+3d
TT3szbL/ANLWJPuvUv8A+SKVePR58mOP2d1cZLcwex2rWA9Gp0lT6hWZ+jpEZPVedas0khK8LBiw
Y8KCus0r3Ni7v+zWHEXd3Zlej37c3FK17Ux3sTHa4K5iDBwhs2pXvTp+qTTp2qNSSiaTMlFm3K6J
Ga98Viw3RFerNHIjtzca2POWXNjjvtfLpxOv3ELaDUvK3M0VrYVv27/ly21IVKI/hojJeDLQ52W3
IEL9jHTLkmIyo5u9wit1WTuwP2quPG0fwEx1y0XJfL57FCVsSdjWHe0zPOlZ2SfwLZFqR5uWYsWI
sKNFgRmzSI+Ou9Fcroio3TzOpGTPMQ/bXpg23Fb/AKhW1l8q6+f8nqab0w2nrHdE/UOD9d55dFh7
3B7y67v+3nJ8bbTB/PFsuadibiPRsxV5VvBbEeuQqbIQYd6VePWbSSLGbOQuD4TdSUa2JBfLJEgR
nb8J6Ne1N9Eb3/DXbJYn5N/RibMxPdddZu/GG97kqVs0i4LmmYtZmZR6zs45Zl7phz+FdBl4Dkht
iK5iO4PVr2NViw/qONOPNtZCZHM3LbSGYnsU1qUOsxMI0v1Ys7ChOndxNZJ06sN7m6tiuknSSQkg
7yc6N3F9PcrW14xTzubBS4MT6TfWFmFmLtqzi2tWbyvOa9QospHh8A50+kNkvGaszGgxmJDgJCVi
x4mjWqiNhL5BYl5578y+YK0C87S2k2K2KWLErWITotnUyFdD6LLwmve9I8Scq6wIUxD0ZDR0B8m5
HOi7itcxHPPRjbPbVrMXgrsV8ulUi1Co4b4q4yyu9c9Rp0NZCowIUGA1y8Eqbr5SLH4WDEdwaNdD
/cxqtTVFhlmgxpz9ZMdlfh1dd4453HVrIxpqMlX7erlNvSouum33ulIkZJSZm1ayK6DMQYiP4FI8
aGx0sipuKqo/d22+vyuYnejV5QbguWtVW4q/VqnITE9U6nNxJucnYrqdO70SLFiKr3uX+3OVVU9I
/Rbk02JuEi/8x6z92nDqnpS9IxVtbZ6wcT8JsRMQrBqmG1WhTFXbbFenKWtQp809su/hPV4jN/g4
roDkVyLutWJ7NVIR7Qrbe3bVfR58vFRs6/rmoWKmIU1+h1qt0+sRZWssWjfxzsVZiE5sVHx4vqj1
ci6uZMKjlXeXXpu3VwjvzBnYI5XJHE+67xvHECrXI+tV2euarx6pPQpiakY0ZJZYsZ7nI2CxzIaN
RdEVjl9qqNt9pyb7I3/2laZ9oebj2gm0LxIyJejgZUJXC6uzVqV/EO2qdSJqtSaNSbk5JlMV0VsB
6oqwYz3Oh6RmaPYjXKxzXaOSGeFONeLv+PYX1aBtIcT8OsXa9MSVSW0MYWXPSqLLQIjeEgzfr6rP
yE3JRXIxWOmYcKDEhOVz0an7FnL6STm7xwwY2a+Wm46dirEt2+LjmXurldwuuedk6RXlWSa9saXj
wlhPiy8TVIrEcm6m/wA2qaKvy9tFm3xXws9H7yk3nbGJ+IduXhcjKG6rV2lXHOSdSqnCUSNFiesT
EOI2JF3oiI92+5dXIirqvOdQ2ge1Kxry9+j05Wpm2sQbplL2xclpmFW7tiVCLGrkSBLuerkZOPcs
ZkR7okPWK1eERsPRHN1XWN+aDGfP1kv2V+HV13ljpcdVsjGmoyVft6uU29Ki66aA90pEjJKTM2rW
RXQZiDER/ApHjQ2OlkVNxVVHy72iW1Ixkyv+js5Zatal7XDLX9i3TYMhWLtmZt01V/V0lYro7mTM
VXRGzERzoekdHcIxGqrXNdo5IY4T43Yupb2F1WgbSHE/DnF6vx5KpOtDGFlz0qiy0CI3hIM36+qz
8hNyUVyMVjpmHCgxITlc9Gp+xZhelWXFdV37I/LXVL2qtm166qjW4UzUapaU2+aodUiOpsVUmZOI
5rVdAitVIjV000dzKqaKsRcjmYKHsPs9FTrsyjqfbmKGAMrXqS170hwZucmaFLVCCqI526rnVCXj
wG8yrrFVET9yoQexty6x8O8lmDuJNRYv6hixWrkmIMVz950aTknyMuxXc2qL6ws37VXVNF/suw4R
arhfbuv9U2XT/wDU07IAAAAAAACkHtYulNzLfFW6Pu80Wu9hJ0Z1r+9V5/llYJggAAAAAAAAGms+
F8Yx4eZWrkquAVnUW/sVoHqzaJRqvMw5eRmFdMQ2xnRXPmJdNGQFiuROGaqua1Of2L5YejzbHTMd
ln2hOJOPePVsUqx41w06el4NOgVaTn4k/NT03CmYsRiSsaMyHBh8E5NHxEdq9uiORFVPxo2yKzCy
fpPDsxETD3cwcW44s9/kCVymL/C6julkf6t6x6zzxlRunBa/3ppzmtsb9jfnWl9uzfGYjCS0rZpE
jJ3DMXBblauCuSTqbVmpLo1ZSNLwY6zbWzDOEg88NmivTV8JP5G9lyV7GbNnm42x0rmizY25buH0
G3KlJ1yFTZCqSk62fmJaEkOTl5SHLzEykGDBdBhPe6NER6827vuc5zO4bS7ZL5m7DzozmI+BWFGW
XHnD+5ahFqUxaV14bWhLz0nHite6M2bm4stKx5mDwrt9kVk5w6qqNiI5GuiROkbMn0fTG+/NpdT8
xuYOw8MMEKLadVZVqbYlmQJKDLR5uBCh+q8BAkYkWBLyzIn8jnvjPjPiQVRWKkThUlJ6ULs7MXNo
plgw5oGDlmtvGuW9cz56cg/qclT3S8s6ViM3t+bjQmqivVibrVVfYumianUs2Po/VwZ+dj1l6w9q
cxTbCxywatiUk5Z1RipMyTYiy0OHNSExGlliIjFfDhuSLCSLurC5muRykH35ANsBO5Y25fIjKm3C
V0qlAWC657Z1Sn8JpwSziRv1BZVGft4LfX+H+LcVn8Z6o7BHYrwNkJgTXodfq9PuXE2+o0GLcE9T
99ZCWhwOESBLSyxGse5jeFiOc9zWq9z/APaiNaTHzDWpPX1gHe1EpcBZup1egT0nKQd9rOGjRJeI
xjd5yo1NXORNVVETXnVEK/Oy/wBlxtLdljbOIt14aYcWJCrF1y0CjzVsXDX6fNR5turnQqjKPgTr
ZdsWXV0VFSYjNTSNzQo3/wBkpfR/fR/b9yp2VizduYFlNp94Ys0KPayUTWRrsSmycWIro8aaWIyY
k48SK9kF7YS8NCVrU4RHK5YbNB3Vsq89OWjEm7KHR8smTXMbb1QhcFSLkm8NrOo/qLNYiNiw4DUp
8RkxuqxXsjNmITXNRGOem8rpBbDzYjYx7KDArF7F+rUy27hzBXVasWUtWzpaahOlJCIjPWGSs1M8
JCgq+LNNgsekKIkKGyBq2M/f/ZqrZv7IfN7iPtxJbNHmHsK3MNpaBMzVbn2SFYkpqDOTD5F8nClp
aDLzUzEaiI9rldFeibrHfuVyoi+gHpDeTrELPVszbkw/wvtpt13jOVamzUpIunZWSVWwplroj0iz
MSHDaqM3va9FVFVE110I8ZSNjhi1O7BG28EblplkWLjRa9WqNZpMG7qDQ7xpECO+dmXw2R2R4E9A
ayLAjKnCwEWLDVyL+5EfCfBzEbZIZ9sZcGImENUykZWKQlRqbIMzibSLetSjVtsBJne4RIslGZwU
BG6a8BJtjrCbuqjnOcjpjYpejM1+PsObey62vetGTE6k3Ol81Gfj8NBo1ZqT4T4MWWVUa6I2EyA9
jIcV0NXOdLtcrIaRHIyMWXvIrtKsAbPw/trDLK/l3wcuS2HQqe7FCQplrTFzxpdzXQYr56bjTU26
IxzYm/EdAl+FckNEai6qx0gNuxsoc12dPI7l3teUSFjlirZ8aozN51iXmaTQpfh5hkBUSCyIspDd
Ca5robFbDR7mw0c9rXOVD6G1n2VGPmZrYh5Y8ILIsNa5iJh6yjpcFJ/W6dLfp/AUiLLxf5o0wyDE
3Yrmt/je7XXVNU5z4e0l2SOYPH3YO5Y8GbSw/wD1bEvD2ZkolwUf9cpsv6g2HJTUJ68PFmGwImj4
jE/jiO111TmRVSdOwVyr37ku2W2HmHOJdB/xq8qFFqbp+n+uy85wCRqjMxof8svEiQnaw4jF/a9d
NdF0VFQkvj/gxR8xOCF2WHcEBkzRLwpMzSJ1jmo5ODjwnQ1VNf7Te1Rf6VEUqWbM3InOXXtq7Jy8
Yl1qHJU3D+9p9Z6Qm5tzJWbjyWsSJCl2P/arppZOC3VERXw0auq7rT3F9KE2eWMO0VytYc23g3aH
+YVig3Q+oT0v+qSVP4CAspFho/emo0Jrv3OamjVVefXTTnNGbUzZJZg8x+xQyq4RWZh/+s4h4aQJ
Blx0r9cpsv8Apqw6a6A/+aLMMgxNIio3+J79famqc58bat7JLMlmO2SWUHCGx8L49dvHDejMbdUv
/kNJlmUeNDkoEBIKxI00xkZXPWJo6C57USEuq87ddTZ19lptIMUskeHOWaZsDDbE7D6xUkqpSrmp
9Sp8lW5HcgxoTKbMPm5yG3+BkXcV0CE5HtZD/nifvRdl7SDYRZhq3sdcs+Bdi0mUxQvTDKpVCcrr
5SrSdPlpVJpYsZGQnzsWDwkOG6LwTV/3ORm9usRUakf822w22kGIuDmF+B8eckMTcIbOk5Odo0NK
pRqay2I8SErIsrMq+IyZjOlt+IxFY+Zh8GreDdqqw2ya2x+w1xuxD2a+VfBjB+2oOI9XwhlJuWr0
xBqslTIXCRIMDeis9cjwt5j4yRd1EVVRETVEO1bWfZUY+ZmdiFlkwgsiw/1zETD5tHS4KT+t06W/
T+ApEWXi/wA0aYZBibsVzW/xvdrrqmqc5rvad7IfMtmB2QuUTB6zcLI9avPDiQirdMv/AJFSZdlG
itgQ4TYSxI00xkZXq56osFz2okNdVTVNdaZ19lptIcUckeHGWaZsDDbE7D6xEkqpSbmp9Sp8lWpH
cgxoTKbMPm5yG3+BkXcV0CE5HNZD/nifvRdtbRrYW5gKrsUcuOAVjUyUxQvrDitzVRrjpOqylPlZ
Vkwk1FVkKJOxYPCQ4b5hITV/3ORu9uNRd1vVts9sEsds02W3KXOYb2AyuYhWBhxI2XeVN/WqZKOk
FlZaXWEnDR5iHDi7sZ823WG96exUXRdV4bY3YKY84rZR8oeHODeH7bujYSWhN025HMr1Okmy8/H9
TiRVRZqYhb6PjtmHIrN5ET/jm1928PKVHoNi0aSmmcHMyklBhRWao7ce1jUVNU5l0VPanMfdAAAA
AAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/yysEwQAAAAAAAADiuv/gIqoq82ga1U9qjX/jmGmqa
BdE5vaY3UZpzcxyT/j+jCLzogavMPanN7Bp+8wqKvtCc/wDQX92plrQq6qE0X2+0x7NFQzvaf+Rp
qmqjTVE/5MNVdef+g393OZTmVDLUCJ/8EANot6N7l22lmN/+ot1re9n3dNQ0h1OctOoy0qla3WsZ
DfMQ5iXjs4RjGI1Hw0YrkX96v0buyhyMZM7U2fuV218JLIj1mbtq02x2ysxVY0ONOx1jR4kd74r4
cOGxzlfFd/tY1ETRNOY24uqM9mqmdVT2c6BP28yexPaYc7dVNF0/5M66/wBahf6MJ7PZzr/3MqvO
ugROfT/3Dm/17DKc3/kwv7l9iBPZ7NDkAAAAAAACkHtYulNzLfFW6Pu80Wu9hJ0Z1r+9V5/llYJg
gAAAAAAAAAAAADQAaAAAAAAaAAAADQAAAAAAAAAAAAFIPaxdKbmW+Kt0fd5otd7CTozrX96rz/LK
wTBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQe1i6U3Mt8Vbo+7zRa72EnRnWv71Xn+WVg
mCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUg9rF0puZb4q3R93mi13sJOjOtf3qvP8srBM
EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYI
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/wAsrBME
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYIA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/yysEwQAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkHtYulNzLfFW6Pu80Wu9hJ0Z1r+9V5/llYJggAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFIPaxdKbmW+Kt0fd5otd7CTozrX96rz/LKwTBAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQe1i6U3Mt8Vbo+7zRa72EnRnWv71Xn+WVgmCAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUg9rF0puZb4q3R93mi13sJOjOtf3qvP8srBMEAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYIAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLXewk6M61/eq8/wAsrBMEAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAApB7WLpTcy3xVuj7vNFrvYSdGda/vVef5ZWCYIAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAABSD2sXSm5lvirdH3eaLA2zy2uNDyQZW5HDW48IsX63VaNX7i
nnT1E/QIkhMwZ2uz8/BdDWPVIMX/AOjNQtUfDaqO3k0XTVd3cojsfqMzAfTtnzocojsfqMzAfTtn
zocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnz
ocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzo
cojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzoc
ojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzoco
jsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocoj
sfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojs
fqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsfqMzAfTtnzocojsf
qMzAfTtnzo/ob6QlZsRqK3AnH/RU1T9tsedDlCFndRGYD5bY86HKELO6iMwHy2x50OUIWd1EZgPl
tjzocoQs7qIzAfLbHnQ5QhZ3URmA+W2POhyhCzuojMB8tsedDlCFndRGYD5bY86HKELO6iMwHy2x
50OUIWd1EZgPltjzocoQs7qIzAfLbHnQ5QhZ3URmA+W2POhyhCzuojMB8tsedDlCFndRGYD5bY86
HKELO6iMwHy2x50OUIWd1EZgPltjzocoQs7qIzAfLbHnQ5QhZ3URmA+W2POhyhCzuojMB8tsedDl
CFndRGYD5bY86HKELO6iMwHy2x50OUIWd1EZgPltjzocoQs7qIzAfLbHnQ5QhZ3URmA+W2POhyhC
zuojMB8tsedDlCFndRGYD5bY86HKELO6iMwHy2x50OUIWd1EZgPltjzocoQs7qIzAfLbHnQ5QhZ3
URmA+W2POhyhCzuojMB8tsedDlCFndRGYD5bY86HKELO6iMwHy2x50OUIWd1EZgPltjzocoQs7qI
zAfLbHnQ5QhZ3URmA+W2POhyhCzuojMB8tsedDlCFndRGYD5bY86HKELO6iMwHy2x50V1M7eSbGD
MlnPxdxFodgVGUol/XrWbjp8CeqtMhzUGXnJ6NMQmRWsmntbERkRqORr3IioujlTnP/Z"
	}]
}');
