// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Lombard.Adapters.MftAdapter.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CreateJobFromFileFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateJobFromFile.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create Job From File", "When an HTTP request for a new DIPS package is received \r\nThen a new voucher outc" +
                    "learings job message will be sent to the Job Service Exchange", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Create Job From File")))
            {
                Lombard.Adapters.MftAdapter.IntegrationTests.Features.CreateJobFromFileFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A valid NSBD file request is received via HTTP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Create Job From File")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Job")]
        public virtual void AValidNSBDFileRequestIsReceivedViaHTTP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A valid NSBD file request is received via HTTP", new string[] {
                        "Job"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("a new JScape processing ID generated is NSBD-2cbabea0-43f9-4554-b118-c80c487d97c3" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("a new voucher outclearings package with file name OUTCLEARINGSPKG_28052015_NSBD68" +
                    "200022.zip is received from JScape with parameter empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("a voucher outclearings job message with id NSBD-2cbabea0-43f9-4554-b118-c80c487d9" +
                    "7c3 is sent to the Job Service Exchange with parameter empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A valid NIEI file request is received via HTTP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Create Job From File")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Job")]
        public virtual void AValidNIEIFileRequestIsReceivedViaHTTP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A valid NIEI file request is received via HTTP", new string[] {
                        "Job"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("a new JScape processing ID generated is NIEI-2cbabea0-43f9-4554-b118-c80c487d97c3" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("a new inwardimageexchange inclearings package with file name IMGEXCH.20120704.201" +
                    "20705.223010.9999999999999999.ANZ.RBA.000005.zip is received from JScape with pa" +
                    "rameter empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("a inwardimageexchange inclearings job message with id NIEI-2cbabea0-43f9-4554-b11" +
                    "8-c80c487d97c3 is sent to the Job Service Exchange with parameter empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A valid NSBP file request is received via HTTP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Create Job From File")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Job")]
        public virtual void AValidNSBPFileRequestIsReceivedViaHTTP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A valid NSBP file request is received via HTTP", new string[] {
                        "Job"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("a new JScape processing ID generated is NSBP-2cbabea0-43f9-4554-b118-c80c487d97c3" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.When("a new voucher outclearings package with file name NONE is received from JScape wi" +
                    "th parameter [{\"name\":\"workType\",\"value\":\"NABCHQ_APOST\"}]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("a voucher outclearings job message with id NSBP-2cbabea0-43f9-4554-b118-c80c487d9" +
                    "7c3 is sent to the Job Service Exchange with parameter [{\"name\":\"workType\",\"valu" +
                    "e\":\"NABCHQ_APOST\"}]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
