//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Lombard.Reporting.AdapterService.Messages.XsdImports
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class AdjustmentLettersDetails {
        
        private string outputFilenamePrefixField;
        
        private CustomerDetails[] customerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string outputFilenamePrefix {
            get {
                return this.outputFilenamePrefixField;
            }
            set {
                this.outputFilenamePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CustomerDetails[] customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class CustomerDetails {
        
        private string bsbField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsb {
            get {
                return this.bsbField;
            }
            set {
                this.bsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class CorporateMetadata {
        
        private CorporateDetails[] corporateDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("corporateDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CorporateDetails[] corporateDetails {
            get {
                return this.corporateDetailsField;
            }
            set {
                this.corporateDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class CorporateDetails {
        
        private string corporateGroupCodeField;
        
        private string corporateNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string corporateGroupCode {
            get {
                return this.corporateGroupCodeField;
            }
            set {
                this.corporateGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string corporateName {
            get {
                return this.corporateNameField;
            }
            set {
                this.corporateNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class EmailEndpointConfiguration {
        
        private string fromField;
        
        private string toField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string endpointNameField;
        
        private string ccField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endpointName {
            get {
                return this.endpointNameField;
            }
            set {
                this.endpointNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cc {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportDefinition {
        
        private DeliveryEndpoint[] deliveryEndpointField;
        
        private FormatType formatTypeField;
        
        private string outputFilenamePatternField;
        
        private ParameterDefinition[] parameterDefinitionsField;
        
        private string reportNameField;
        
        private string reportTypeField;
        
        private BatchTypeCode[] batchTypeCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deliveryEndpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryEndpoint[] deliveryEndpoint {
            get {
                return this.deliveryEndpointField;
            }
            set {
                this.deliveryEndpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormatType formatType {
            get {
                return this.formatTypeField;
            }
            set {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string outputFilenamePattern {
            get {
                return this.outputFilenamePatternField;
            }
            set {
                this.outputFilenamePatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameterDefinitions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ParameterDefinition[] parameterDefinitions {
            get {
                return this.parameterDefinitionsField;
            }
            set {
                this.parameterDefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportName {
            get {
                return this.reportNameField;
            }
            set {
                this.reportNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("batchTypeCodes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BatchTypeCode[] batchTypeCodes {
            get {
                return this.batchTypeCodesField;
            }
            set {
                this.batchTypeCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class DeliveryEndpoint {
        
        private DeliveryEndpointType endpointTypeField;
        
        private string endpointNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryEndpointType endpointType {
            get {
                return this.endpointTypeField;
            }
            set {
                this.endpointTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endpointName {
            get {
                return this.endpointNameField;
            }
            set {
                this.endpointNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    public enum DeliveryEndpointType {
        
        /// <remarks/>
        coin,
        
        /// <remarks/>
        email,
        
        /// <remarks/>
        b2b,
        
        /// <remarks/>
        documentum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    public enum FormatType {
        
        /// <remarks/>
        CSV,
        
        /// <remarks/>
        DAT,
        
        /// <remarks/>
        TXT,
        
        /// <remarks/>
        XLSX,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        DOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ParameterDefinition {
        
        private ParameterType metadataNameField;
        
        private string ssrsNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ParameterType metadataName {
            get {
                return this.metadataNameField;
            }
            set {
                this.metadataNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ssrsName {
            get {
                return this.ssrsNameField;
            }
            set {
                this.ssrsNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    public enum ParameterType {
        
        /// <remarks/>
        AgencyBank,
        
        /// <remarks/>
        AgencyBankGroup,
        
        /// <remarks/>
        BatchType,
        
        /// <remarks/>
        BusinessDay,
        
        /// <remarks/>
        CorporateGroup,
        
        /// <remarks/>
        FinancialInstitution,
        
        /// <remarks/>
        StartMonthDate,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        StateOrdinal,
        
        /// <remarks/>
        SystemDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class BatchTypeCode {
        
        private string batchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchType {
            get {
                return this.batchTypeField;
            }
            set {
                this.batchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportAgencyBanksMetadata {
        
        private ReportAgencyBanksDetails[] agencyBanksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agencyBanks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReportAgencyBanksDetails[] agencyBanks {
            get {
                return this.agencyBanksField;
            }
            set {
                this.agencyBanksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportAgencyBanksDetails {
        
        private string agencyBankGroupCodeField;
        
        private string agencyBankNameField;
        
        private string[] includeReportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agencyBankGroupCode {
            get {
                return this.agencyBankGroupCodeField;
            }
            set {
                this.agencyBankGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agencyBankName {
            get {
                return this.agencyBankNameField;
            }
            set {
                this.agencyBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includeReports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] includeReports {
            get {
                return this.includeReportsField;
            }
            set {
                this.includeReportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportGroup {
        
        private ReportEventTypeEnum eventTypeField;
        
        private ReportDefinition[] reportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReportEventTypeEnum eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReportDefinition[] reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    public enum ReportEventTypeEnum {
        
        /// <remarks/>
        EndOfDay,
        
        /// <remarks/>
        EndOfDayRecon,
        
        /// <remarks/>
        EndOfMonth,
        
        /// <remarks/>
        NABCHQ_LBOX,
        
        /// <remarks/>
        StartOfDay,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportRequest {
        
        private ReportEventTypeEnum eventTypeField;
        
        private System.DateTime businessDayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReportEventTypeEnum eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime businessDay {
            get {
                return this.businessDayField;
            }
            set {
                this.businessDayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class ReportMetadata {
        
        private ReportGroup[] reportGroupsField;
        
        private EmailEndpointConfiguration[] emailConfigurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportGroups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReportGroup[] reportGroups {
            get {
                return this.reportGroupsField;
            }
            set {
                this.reportGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmailEndpointConfiguration[] emailConfiguration {
            get {
                return this.emailConfigurationField;
            }
            set {
                this.emailConfigurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting/metadata", IsNullable=false)]
    public partial class AdjustmentLettersMetadata {
        
        private AdjustmentLettersDetails[] lettersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("letters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdjustmentLettersDetails[] letters {
            get {
                return this.lettersField;
            }
            set {
                this.lettersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting", IsNullable=false)]
    public partial class Parameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting", IsNullable=false)]
    public partial class ExecuteBatchReportRequest {
        
        private string batchNameField;
        
        private string jobIdentifierField;
        
        private ExecuteReportRequest[] reportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchName {
            get {
                return this.batchNameField;
            }
            set {
                this.batchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobIdentifier {
            get {
                return this.jobIdentifierField;
            }
            set {
                this.jobIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExecuteReportRequest[] reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting", IsNullable=false)]
    public partial class ExecuteReportRequest {
        
        private string outputFilenameField;
        
        private FormatType outputFormatTypeField;
        
        private Parameter[] parametersField;
        
        private string reportNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string outputFilename {
            get {
                return this.outputFilenameField;
            }
            set {
                this.outputFilenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormatType outputFormatType {
            get {
                return this.outputFormatTypeField;
            }
            set {
                this.outputFormatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Parameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportName {
            get {
                return this.reportNameField;
            }
            set {
                this.reportNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/reporting", IsNullable=false)]
    public partial class ExecuteBatchReportResponse {
    }
}
