// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Lombard.Adapters.DipsAdapter.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CorrectCodelineFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CorrectCodeline.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Correct Codeline", "Given a valid codeline\r\nWhen a codeline correction request is issued to DIPS\r\nThe" +
                    " codeline correction request batch should be viewable in DIPS", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Correct Codeline")))
            {
                Lombard.Adapters.DipsAdapter.IntegrationTests.Features.CorrectCodelineFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Auto correct a good codeline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Correct Codeline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CorrectCodeline")]
        public virtual void AutoCorrectAGoodCodeline()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Auto correct a good codeline", new string[] {
                        "CorrectCodeline"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("there are no CorrectCodeline rows for batch number 58300013", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "auxDom",
                        "extraAuxDom",
                        "bsbNumber",
                        "accountNumber",
                        "transactionCode",
                        "documentReferenceNumber",
                        "imageRotation",
                        "capturedAmount",
                        "amountConfidenceLevel",
                        "amountRegionOfInterest",
                        "workType",
                        "processingDate",
                        "collectingBank"});
            table1.AddRow(new string[] {
                        "001193",
                        "",
                        "013812",
                        "256902729",
                        "50",
                        "000111222",
                        "",
                        "45.67",
                        "1000",
                        "",
                        "NABCHQ_POD",
                        "2015/03/17",
                        "123456"});
            table1.AddRow(new string[] {
                        "001193",
                        "",
                        "092002",
                        "814649",
                        "50",
                        "000111223",
                        "",
                        "2341.45",
                        "785",
                        "",
                        "NABCHQ_POD",
                        "2015/03/17",
                        "123456"});
#line 9
 testRunner.And("a CorrectBatchCodelineRequest with batch number 58300013 is added to the queue fo" +
                    "r the following CorrectCodeline vouchers:", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "workType",
                        "NABCHQ_POD"});
            table2.AddRow(new string[] {
                        "processingState",
                        "SA"});
            table2.AddRow(new string[] {
                        "scannedBatchNumber",
                        "58300013"});
            table2.AddRow(new string[] {
                        "captureBSB",
                        "085384"});
            table2.AddRow(new string[] {
                        "collectingBank",
                        "123456"});
            table2.AddRow(new string[] {
                        "unitID",
                        "123"});
#line 13
 testRunner.And("a CorrectBatchCodelineRequest with batch number 58300013 contains this voucher ba" +
                    "tch:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "CorrelationId",
                        "NSBD-6e5bc63b-be84-4053-a4ce-191abbd69f27"});
            table3.AddRow(new string[] {
                        "RoutingKey",
                        "NSBD"});
            table3.AddRow(new string[] {
                        "PublishTimeOutSeconds",
                        "3"});
#line 21
 testRunner.When("the message is published to the queue and CorrectBatchCodelineRequest process the" +
                    " message with this information:", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "S_LOCATION",
                        "CodelineCorrect"});
            table4.AddRow(new string[] {
                        "S_LOCK",
                        "0"});
            table4.AddRow(new string[] {
                        "S_CLIENT",
                        "NabChq"});
            table4.AddRow(new string[] {
                        "S_JOB_ID",
                        "NabChqPod"});
            table4.AddRow(new string[] {
                        "S_MODIFIED",
                        "0"});
            table4.AddRow(new string[] {
                        "S_COMPLETE",
                        "0"});
            table4.AddRow(new string[] {
                        "S_BATCH",
                        "58300013"});
            table4.AddRow(new string[] {
                        "S_TRACE",
                        "000111222"});
            table4.AddRow(new string[] {
                        "S_PRIORITY",
                        "5"});
            table4.AddRow(new string[] {
                        "S_VERSION",
                        "4.0.2.152"});
            table4.AddRow(new string[] {
                        "S_SDATE",
                        "17/03/15"});
            table4.AddRow(new string[] {
                        "RoutingKey",
                        "NSBD"});
#line 26
 testRunner.Then("a DipsQueue table row will exist with the following CorrectCodeline values", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "S_BATCH",
                        "S_TRACE",
                        "S_LENGTH",
                        "batch",
                        "trace",
                        "proc_date",
                        "ead",
                        "ser_num",
                        "bsb_num",
                        "acc_num",
                        "trancode",
                        "amount",
                        "job_id",
                        "processing_state",
                        "captureBSB",
                        "collecting_bank",
                        "unit_id",
                        "amountConfidenceLevel"});
            table5.AddRow(new string[] {
                        "58300013",
                        "000111222",
                        "01025",
                        "58300013",
                        "000111222",
                        "20150317",
                        "",
                        "001193",
                        "013812",
                        "256902729",
                        "50",
                        "45.67",
                        "NabChqPod",
                        "SA",
                        "085384",
                        "123456",
                        "123",
                        "999"});
            table5.AddRow(new string[] {
                        "58300013",
                        "000111223",
                        "01025",
                        "58300013",
                        "000111223",
                        "20150317",
                        "",
                        "001193",
                        "092002",
                        "814649",
                        "50",
                        "2341.45",
                        "NabChqPod",
                        "SA",
                        "085384",
                        "123456",
                        "123",
                        "785"});
#line 40
 testRunner.And("DipsNabChq table rows will exist with the following CorrectCodeline values", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "BATCH",
                        "TRACE",
                        "TABLE_NO"});
            table6.AddRow(new string[] {
                        "58300013",
                        "000111222",
                        "0"});
            table6.AddRow(new string[] {
                        "58300013",
                        "000111223",
                        "0"});
#line 44
 testRunner.And("DipsDbIndex table rows will exist with the following CorrectCodeline values - tra" +
                    "ce", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Auto correct a good codeline with a long DRN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Correct Codeline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CorrectCodeline")]
        public virtual void AutoCorrectAGoodCodelineWithALongDRN()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Auto correct a good codeline with a long DRN", new string[] {
                        "CorrectCodeline"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
 testRunner.Given("there are no CorrectCodeline rows for batch number 58300015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "auxDom",
                        "extraAuxDom",
                        "bsbNumber",
                        "accountNumber",
                        "transactionCode",
                        "documentReferenceNumber",
                        "imageRotation",
                        "capturedAmount",
                        "amountConfidenceLevel",
                        "amountRegionOfInterest",
                        "workType",
                        "processingDate",
                        "collectingBank",
                        "repostFromDRN"});
            table7.AddRow(new string[] {
                        "001193",
                        "",
                        "013812",
                        "256902729",
                        "50",
                        "000000111222",
                        "",
                        "45.67",
                        "",
                        "",
                        "NABCHQ_POD",
                        "2015/03/17",
                        "123456",
                        "000000111222"});
            table7.AddRow(new string[] {
                        "001193",
                        "",
                        "092002",
                        "814649",
                        "50",
                        "000000111223",
                        "",
                        "2341.45",
                        "",
                        "",
                        "NABCHQ_POD",
                        "2015/03/18",
                        "123456",
                        "000000111223"});
#line 52
 testRunner.And("a CorrectBatchCodelineRequest with batch number 58300015 is added to the queue fo" +
                    "r the following CorrectCodeline vouchers:", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "workType",
                        "NABCHQ_POD"});
            table8.AddRow(new string[] {
                        "processingState",
                        "SA"});
            table8.AddRow(new string[] {
                        "scannedBatchNumber",
                        "58300015"});
            table8.AddRow(new string[] {
                        "captureBSB",
                        "085384"});
            table8.AddRow(new string[] {
                        "collectingBank",
                        "123456"});
            table8.AddRow(new string[] {
                        "unitID",
                        "123"});
#line 56
 testRunner.And("a CorrectBatchCodelineRequest with batch number 58300015 contains this voucher ba" +
                    "tch:", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "CorrelationId",
                        "NSBD-6e5bc63b-be84-4053-a4ce-191abbd69f28"});
            table9.AddRow(new string[] {
                        "RoutingKey",
                        "NSBD"});
            table9.AddRow(new string[] {
                        "PublishTimeOutSeconds",
                        "3"});
#line 64
 testRunner.When("the message is published to the queue and CorrectBatchCodelineRequest process the" +
                    " message with this information:", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "S_LOCATION",
                        "CodelineCorrect"});
            table10.AddRow(new string[] {
                        "S_LOCK",
                        "0"});
            table10.AddRow(new string[] {
                        "S_CLIENT",
                        "NabChq"});
            table10.AddRow(new string[] {
                        "S_JOB_ID",
                        "NabChqPod"});
            table10.AddRow(new string[] {
                        "S_MODIFIED",
                        "0"});
            table10.AddRow(new string[] {
                        "S_COMPLETE",
                        "0"});
            table10.AddRow(new string[] {
                        "S_BATCH",
                        "58300015"});
            table10.AddRow(new string[] {
                        "S_PRIORITY",
                        "5"});
            table10.AddRow(new string[] {
                        "S_VERSION",
                        "4.0.2.152"});
            table10.AddRow(new string[] {
                        "S_SDATE",
                        "17/03/15"});
#line 69
 testRunner.Then("a DipsQueue table row will exist with the following CorrectCodeline values", ((string)(null)), table10, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "S_BATCH",
                        "S_LENGTH",
                        "batch",
                        "proc_date",
                        "ead",
                        "ser_num",
                        "bsb_num",
                        "acc_num",
                        "trancode",
                        "amount",
                        "job_id",
                        "processing_state",
                        "captureBSB",
                        "collecting_bank",
                        "unit_id",
                        "repostFromDRN"});
            table11.AddRow(new string[] {
                        "58300015",
                        "01025",
                        "58300015",
                        "20150317",
                        "",
                        "001193",
                        "013812",
                        "256902729",
                        "50",
                        "45.67",
                        "NabChqPod",
                        "SA",
                        "085384",
                        "123456",
                        "123",
                        "000000111222"});
            table11.AddRow(new string[] {
                        "58300015",
                        "01025",
                        "58300015",
                        "20150318",
                        "",
                        "001193",
                        "092002",
                        "814649",
                        "50",
                        "2341.45",
                        "NabChqPod",
                        "SA",
                        "085384",
                        "123456",
                        "123",
                        "000000111223"});
#line 81
 testRunner.And("DipsNabChq table rows will exist with the following CorrectCodeline values - long" +
                    " Drn", ((string)(null)), table11, "And ");
#line 85
 testRunner.And("DipsDbIndex table rows will exist with batch number 58300015", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
