Feature: GetVouchersInformationResponse
	Given a valid response from documentum
	A response should be returned to DIPS with all relevant voucher information

@GetVouchersInformationResponse
Scenario: Get Vouchers Information Response
    Given there are no GetVouchersInformationResponse rows for guid SurplusItem_0093999d-4a95-4294-bbae-5e272c95e654
	And a GetVouchersInformationResponse contains the following vouchers:
	| accountNumber | amount | auxDom | bsbNumber | documentReferenceNumber | documentType | extraAuxDom | processingDate | transactionCode |
	| 256902729     | 45.67  | 013812 | 256902729 | 900111222               | CRT          |             | 15092015       | 62              |
	And a GetVouchersInformationResponse contains the following voucher batch:
	| batchAccountNumber | batchType    | captureBsb | client | collectingBank | processingState | scannedBatchNumber | source | subBatchType | unitID | workType       |
	| 58300013           | OTC_Vouchers | 013812     | NAB    | 900111222      | VIC             | 58300013           | DIPS   | OTC_Vouchers | 065    | NABCHQ_SURPLUS |
	And a GetVouchersInformationResponse contains the following voucher process:
	| Field                            | Value                |
	| adjustedBy                       | a                    |
	| adjustedFlag                     | 0                    |
	| adjustmentDescription            | Adjustment < $10     |
	| adjustmentLetterRequired         | 0                    |
	| adjustmentReasonCode             | 0                    |
	| apPresentmentType                | 0                    |
	| customerLinkNumber               | 12345                |
	| documentRetrievalFlag            | 0                    |
	| forValueType                     | Inward_Non_For_Value |
	| highValueFlag                    | 0                    |
	| inactiveFlag                     | 0                    |
	| isGeneratedBulkCredit            | 0                    |
	| insertedCreditType               | POSTED_SUSPENSE_CREDIT |
	| isGeneratedVoucher               | 0                    |
	| isReservedForBalancing           | 0                    |
	| isRetrievedVoucher               | 0                    |
	| listingPageNumber                | 0                    |
	| manualRepair                     | 0                    |
	| micrFlag                         | 0                    |
	| operatorId                       | a                    |
	| postTransmissionQaAmountFlag     | 0                    |
	| postTransmissionQaCodelineFlag   | 0                    |
	| preAdjustmentAmount              | 0                    |
	| presentationMode                 | 0                    |
	| rawMICR                          | 12345                |
	| rawOCR                           | 12345                |
	| releaseFlag                      | 0                    |
	| repostFromDRN                    | 12345                |
	| repostFromProcessingDate         | 20092015             |
	| surplusItemFlag                  | 0                    |
	| suspectFraud                     | 0                    |
	| thirdPartyCheckFailed            | 0                    |
	| thirdPartyMixedDepositReturnFlag | 0                    |
	| thirdPartyPoolFlag               | 0                    |
	| transactionLinkNumber            | 1                    |
	| unencodedECDReturnFlag           | 0                    |
	| unprocessable                    | 0                    |
	| voucherDelayedIndicator          | 0                    |
	When the message is published to the queue and GetVouchersInformationResponse process the message with this information:
	| Field                 | Value                                            |
	| CorrelationId         | SurplusItem_0093999d-4a95-4294-bbae-5e272c95e654 |
	| RoutingKey            | NSBD                                             |
	| PublishTimeOutSeconds | 3                                                |
	Then a DipsResponseData table row will exist with the following values
	| Field          | Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
	| guid_name      | SurplusItem_0093999d-4a95-4294-bbae-5e272c95e654                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
	| doc_ref_number | 900111222                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
	| payload        | [{"name":"accountNumber","value":"256902729"},{"name":"amount","value":"45.67"},{"name":"auxDom","value":"013812"},{"name":"bsbNumber","value":"256902729"},{"name":"documentReferenceNumber","value":"900111222"},{"name":"documentType","value":"CRT"},{"name":"extraAuxDom","value":""},{"name":"processingDate","value":"01/01/0001 00:00:00"},{"name":"transactionCode","value":"62"},{"name":"batchAccountNumber","value":"58300013"},{"name":"batchType","value":"OTC_Vouchers"},{"name":"captureBsb","value":"013812"},{"name":"client","value":"NAB"},{"name":"collectingBank","value":"900111222"},{"name":"processingState","value":"VIC"},{"name":"scannedBatchNumber","value":"58300013"},{"name":"source","value":"DIPS"},{"name":"subBatchType","value":"OTC_Vouchers"},{"name":"unitID","value":"065"},{"name":"workType","value":"NABCHQ_SURPLUS"},{"name":"adjustedBy","value":null},{"name":"adjustedFlag","value":"False"},{"name":"adjustmentDescription","value":null},{"name":"adjustmentLetterRequired","value":"False"},{"name":"adjustmentReasonCode","value":"0"},{"name":"apPresentmentType","value":""},{"name":"customerLinkNumber","value":null},{"name":"documentRetrievalFlag","value":"False"},{"name":"forValueType","value":""},{"name":"highValueFlag","value":"False"},{"name":"inactiveFlag","value":"False"},{"name":"isGeneratedBulkCredit","value":"False"},{"name":"insertedCreditType","value":""},{"name":"isGeneratedVoucher","value":"False"},{"name":"isReservedForBalancing","value":"False"},{"name":"isRetrievedVoucher","value":"False"},{"name":"listingPageNumber","value":null},{"name":"manualRepair","value":"0"},{"name":"micrFlag","value":"False"},{"name":"operatorId","value":null},{"name":"postTransmissionQaAmountFlag","value":"False"},{"name":"postTransmissionQaCodelineFlag","value":"False"},{"name":"preAdjustmentAmount","value":null},{"name":"presentationMode","value":null},{"name":"rawMICR","value":null},{"name":"rawOCR","value":null},{"name":"releaseFlag","value":""},{"name":"repostFromDRN","value":null},{"name":"repostFromProcessingDate","value":""},{"name":"surplusItemFlag","value":"False"},{"name":"suspectFraud","value":"False"},{"name":"thirdPartyCheckFailed","value":"False"},{"name":"thirdPartyMixedDepositReturnFlag","value":"False"},{"name":"thirdPartyPoolFlag","value":"False"},{"name":"transactionLinkNumber","value":null},{"name":"unencodedECDReturnFlag","value":"False"},{"name":"unprocessable","value":"False"},{"name":"voucherDelayedIndicator","value":null}] |
	And a DipsResponseDone table row will exist with the following values
	| Field             | Value                                            |
	| guid_name         | SurplusItem_0093999d-4a95-4294-bbae-5e272c95e654 |
	| number_of_results | 1                                                |