//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Lombard.Adapters.A2iaAdapter.Messages.XsdImports {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class RegionOfInterest {
        
        private int topField;
        
        private int leftField;
        
        private int heightField;
        
        private int widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class Voucher {
        
        private string transactionCodeField;
        
        private string documentReferenceNumberField;
        
        private string bsbNumberField;
        
        private string accountNumberField;
        
        private DocumentTypeEnum documentTypeField;
        
        private string auxDomField;
        
        private System.DateTime processingDateField;
        
        private string amountField;
        
        private string extraAuxDomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentReferenceNumber {
            get {
                return this.documentReferenceNumberField;
            }
            set {
                this.documentReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsbNumber {
            get {
                return this.bsbNumberField;
            }
            set {
                this.bsbNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentTypeEnum documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auxDom {
            get {
                return this.auxDomField;
            }
            set {
                this.auxDomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime processingDate {
            get {
                return this.processingDateField;
            }
            set {
                this.processingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extraAuxDom {
            get {
                return this.extraAuxDomField;
            }
            set {
                this.extraAuxDomField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum DocumentTypeEnum {
        
        /// <remarks/>
        CRT,
        
        /// <remarks/>
        SUP,
        
        /// <remarks/>
        DBT,
        
        /// <remarks/>
        HDR,
        
        /// <remarks/>
        Bh,
        
        /// <remarks/>
        Cr,
        
        /// <remarks/>
        Dr,
        
        /// <remarks/>
        Sp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class CodelineStatus {
        
        private bool transactionCodeStatusField;
        
        private bool bsbNumberStatusField;
        
        private bool accountNumberStatusField;
        
        private bool auxDomStatusField;
        
        private bool amountStatusField;
        
        private bool extraAuxDomStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool transactionCodeStatus {
            get {
                return this.transactionCodeStatusField;
            }
            set {
                this.transactionCodeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bsbNumberStatus {
            get {
                return this.bsbNumberStatusField;
            }
            set {
                this.bsbNumberStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool accountNumberStatus {
            get {
                return this.accountNumberStatusField;
            }
            set {
                this.accountNumberStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool auxDomStatus {
            get {
                return this.auxDomStatusField;
            }
            set {
                this.auxDomStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool amountStatus {
            get {
                return this.amountStatusField;
            }
            set {
                this.amountStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool extraAuxDomStatus {
            get {
                return this.extraAuxDomStatusField;
            }
            set {
                this.extraAuxDomStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherBatch {
        
        private string collectingBankField;
        
        private string clientField;
        
        private string sourceField;
        
        private StateEnum processingStateField;
        
        private string batchAccountNumberField;
        
        private WorkTypeEnum workTypeField;
        
        private string captureBsbField;
        
        private string unitIDField;
        
        private string scannedBatchNumberField;
        
        private string batchTypeField;
        
        private string subBatchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string collectingBank {
            get {
                return this.collectingBankField;
            }
            set {
                this.collectingBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StateEnum processingState {
            get {
                return this.processingStateField;
            }
            set {
                this.processingStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchAccountNumber {
            get {
                return this.batchAccountNumberField;
            }
            set {
                this.batchAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkTypeEnum workType {
            get {
                return this.workTypeField;
            }
            set {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string captureBsb {
            get {
                return this.captureBsbField;
            }
            set {
                this.captureBsbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitID {
            get {
                return this.unitIDField;
            }
            set {
                this.unitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scannedBatchNumber {
            get {
                return this.scannedBatchNumberField;
            }
            set {
                this.scannedBatchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchType {
            get {
                return this.batchTypeField;
            }
            set {
                this.batchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subBatchType {
            get {
                return this.subBatchTypeField;
            }
            set {
                this.subBatchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum StateEnum {
        
        /// <remarks/>
        NSW,
        
        /// <remarks/>
        QLD,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        VIC,
        
        /// <remarks/>
        WA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum WorkTypeEnum {
        
        /// <remarks/>
        BQL_INWARDFV,
        
        /// <remarks/>
        BQL_POD,
        
        /// <remarks/>
        NABCHQ_APOST,
        
        /// <remarks/>
        NABCHQ_INWARDFV,
        
        /// <remarks/>
        NABCHQ_INWARDNFV,
        
        /// <remarks/>
        NABCHQ_LBOX,
        
        /// <remarks/>
        NABCHQ_LISTINGS,
        
        /// <remarks/>
        NABCHQ_POD,
        
        /// <remarks/>
        NABCHQ_SURPLUS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherProcess {
        
        private string voucherDelayedIndicatorField;
        
        private bool micrFlagField;
        
        private bool unprocessableField;
        
        private string transactionLinkNumberField;
        
        private ForValueTypeEnum forValueTypeField;
        
        private string presentationModeField;
        
        private int manualRepairField;
        
        private bool inactiveFlagField;
        
        private bool highValueFlagField;
        
        private string rawMICRField;
        
        private string rawOCRField;
        
        private bool suspectFraudField;
        
        private string listingPageNumberField;
        
        private int adjustmentReasonCodeField;
        
        private string adjustmentDescriptionField;
        
        private string adjustedByField;
        
        private bool adjustmentsOnHoldField;
        
        private bool adjustedFlagField;
        
        private bool adjustmentLetterRequiredField;
        
        private string repostFromDRNField;
        
        private System.DateTime repostFromProcessingDateField;
        
        private bool repostFromProcessingDateFieldSpecified;
        
        private bool surplusItemFlagField;
        
        private bool thirdPartyCheckFailedField;
        
        private string preAdjustmentAmountField;
        
        private bool unencodedECDReturnFlagField;
        
        private bool thirdPartyPoolFlagField;
        
        private bool isGeneratedVoucherField;
        
        private bool isGeneratedVoucherFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string voucherDelayedIndicator {
            get {
                return this.voucherDelayedIndicatorField;
            }
            set {
                this.voucherDelayedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool micrFlag {
            get {
                return this.micrFlagField;
            }
            set {
                this.micrFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool unprocessable {
            get {
                return this.unprocessableField;
            }
            set {
                this.unprocessableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionLinkNumber {
            get {
                return this.transactionLinkNumberField;
            }
            set {
                this.transactionLinkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForValueTypeEnum forValueType {
            get {
                return this.forValueTypeField;
            }
            set {
                this.forValueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presentationMode {
            get {
                return this.presentationModeField;
            }
            set {
                this.presentationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int manualRepair {
            get {
                return this.manualRepairField;
            }
            set {
                this.manualRepairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool inactiveFlag {
            get {
                return this.inactiveFlagField;
            }
            set {
                this.inactiveFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool highValueFlag {
            get {
                return this.highValueFlagField;
            }
            set {
                this.highValueFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rawMICR {
            get {
                return this.rawMICRField;
            }
            set {
                this.rawMICRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rawOCR {
            get {
                return this.rawOCRField;
            }
            set {
                this.rawOCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool suspectFraud {
            get {
                return this.suspectFraudField;
            }
            set {
                this.suspectFraudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string listingPageNumber {
            get {
                return this.listingPageNumberField;
            }
            set {
                this.listingPageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adjustmentReasonCode {
            get {
                return this.adjustmentReasonCodeField;
            }
            set {
                this.adjustmentReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adjustmentDescription {
            get {
                return this.adjustmentDescriptionField;
            }
            set {
                this.adjustmentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adjustedBy {
            get {
                return this.adjustedByField;
            }
            set {
                this.adjustedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool adjustmentsOnHold {
            get {
                return this.adjustmentsOnHoldField;
            }
            set {
                this.adjustmentsOnHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool adjustedFlag {
            get {
                return this.adjustedFlagField;
            }
            set {
                this.adjustedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool adjustmentLetterRequired {
            get {
                return this.adjustmentLetterRequiredField;
            }
            set {
                this.adjustmentLetterRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string repostFromDRN {
            get {
                return this.repostFromDRNField;
            }
            set {
                this.repostFromDRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime repostFromProcessingDate {
            get {
                return this.repostFromProcessingDateField;
            }
            set {
                this.repostFromProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool repostFromProcessingDateSpecified {
            get {
                return this.repostFromProcessingDateFieldSpecified;
            }
            set {
                this.repostFromProcessingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool surplusItemFlag {
            get {
                return this.surplusItemFlagField;
            }
            set {
                this.surplusItemFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool thirdPartyCheckFailed {
            get {
                return this.thirdPartyCheckFailedField;
            }
            set {
                this.thirdPartyCheckFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string preAdjustmentAmount {
            get {
                return this.preAdjustmentAmountField;
            }
            set {
                this.preAdjustmentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool unencodedECDReturnFlag {
            get {
                return this.unencodedECDReturnFlagField;
            }
            set {
                this.unencodedECDReturnFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool thirdPartyPoolFlag {
            get {
                return this.thirdPartyPoolFlagField;
            }
            set {
                this.thirdPartyPoolFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGeneratedVoucher {
            get {
                return this.isGeneratedVoucherField;
            }
            set {
                this.isGeneratedVoucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isGeneratedVoucherSpecified {
            get {
                return this.isGeneratedVoucherFieldSpecified;
            }
            set {
                this.isGeneratedVoucherFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    public enum ForValueTypeEnum {
        
        /// <remarks/>
        Inward_For_Value,
        
        /// <remarks/>
        Inward_Non_For_Value,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/common/Voucher", IsNullable=false)]
    public partial class VoucherInformation {
        
        private Voucher voucherField;
        
        private VoucherBatch voucherBatchField;
        
        private VoucherProcess voucherProcessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Voucher voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherBatch voucherBatch {
            get {
                return this.voucherBatchField;
            }
            set {
                this.voucherBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VoucherProcess voucherProcess {
            get {
                return this.voucherProcessField;
            }
            set {
                this.voucherProcessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount", IsNullable=false)]
    public partial class RecogniseBatchCourtesyAmountRequest {
        
        private RecogniseCourtesyAmountRequest[] voucherField;
        
        private string jobIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voucher", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecogniseCourtesyAmountRequest[] voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobIdentifier {
            get {
                return this.jobIdentifierField;
            }
            set {
                this.jobIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount", IsNullable=false)]
    public partial class RecogniseCourtesyAmountRequest {
        
        private string documentReferenceNumberField;
        
        private System.DateTime processingDateField;
        
        private string transactionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentReferenceNumber {
            get {
                return this.documentReferenceNumberField;
            }
            set {
                this.documentReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime processingDate
        {
            get
            {
                return this.processingDateField;
            }
            set
            {
                this.processingDateField = value;
            }
        }

        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        //public string processingDate { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount", IsNullable=false)]
    public partial class RecogniseBatchCourtesyAmountResponse {
        
        private RecogniseCourtesyAmountResponse[] voucherField;
        
        private string jobIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voucher", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecogniseCourtesyAmountResponse[] voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobIdentifier {
            get {
                return this.jobIdentifierField;
            }
            set {
                this.jobIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://lombard.aus.fujixerox.com/outclearings/RecogniseCourtesyAmount", IsNullable=false)]
    public partial class RecogniseCourtesyAmountResponse {
        
        private string documentReferenceNumberField;
        
        private string imageRotationField;
        
        private string capturedAmountField;
        
        private string amountConfidenceLevelField;
        
        private RegionOfInterest amountRegionOfInterestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentReferenceNumber {
            get {
                return this.documentReferenceNumberField;
            }
            set {
                this.documentReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageRotation {
            get {
                return this.imageRotationField;
            }
            set {
                this.imageRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string capturedAmount {
            get {
                return this.capturedAmountField;
            }
            set {
                this.capturedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amountConfidenceLevel {
            get {
                return this.amountConfidenceLevelField;
            }
            set {
                this.amountConfidenceLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RegionOfInterest amountRegionOfInterest {
            get {
                return this.amountRegionOfInterestField;
            }
            set {
                this.amountRegionOfInterestField = value;
            }
        }
    }
}
